package com.kjnext.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * RaAclMaster generated by MyEclipse - Hibernate Tools
 */

public class RaAclMaster  implements java.io.Serializable {


    // Fields    

     private Integer aclId;
     private RaSubModule raSubModule;
     private String action;
     private Set raUserAcls = new HashSet(0);


    // Constructors

    /** default constructor */
    public RaAclMaster() {
    }

	/** minimal constructor */
    public RaAclMaster(Integer aclId) {
        this.aclId = aclId;
    }
    
    /** full constructor */
    public RaAclMaster(Integer aclId, RaSubModule raSubModule, String action, Set raUserAcls) {
        this.aclId = aclId;
        this.raSubModule = raSubModule;
        this.action = action;
        this.raUserAcls = raUserAcls;
    }

   
    // Property accessors

    public Integer getAclId() {
        return this.aclId;
    }
    
    public void setAclId(Integer aclId) {
        this.aclId = aclId;
    }

    public RaSubModule getRaSubModule() {
        return this.raSubModule;
    }
    
    public void setRaSubModule(RaSubModule raSubModule) {
        this.raSubModule = raSubModule;
    }

    public String getAction() {
        return this.action;
    }
    
    public void setAction(String action) {
        this.action = action;
    }

    public Set getRaUserAcls() {
        return this.raUserAcls;
    }
    
    public void setRaUserAcls(Set raUserAcls) {
        this.raUserAcls = raUserAcls;
    }
   








}