package com.kjnext.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * RaBussinessTypeMaster generated by MyEclipse - Hibernate Tools
 */

public class RaBussinessTypeMaster  implements java.io.Serializable {


    // Fields    

     private Integer buisnessTypeId;
     private String description;
     private String bussStatus;
     private String buisnessType;
     private Set raBussSupplyProds = new HashSet(0);
     private Set raRequestBusses = new HashSet(0);
     private Set raCompanyBussinesses = new HashSet(0);
     private Integer[] companyBussiness; 

    // Constructors

    /** default constructor */
    public RaBussinessTypeMaster() {
    }

	/** minimal constructor */
    public RaBussinessTypeMaster(Integer buisnessTypeId) {
        this.buisnessTypeId = buisnessTypeId;
    }
    
    /** full constructor */
    public RaBussinessTypeMaster(Integer buisnessTypeId, String description, String bussStatus, String buisnessType, Set raBussSupplyProds, Set raRequestBusses, Set raCompanyBussinesses) {
        this.buisnessTypeId = buisnessTypeId;
        this.description = description;
        this.bussStatus = bussStatus;
        this.buisnessType = buisnessType;
        this.raBussSupplyProds = raBussSupplyProds;
        this.raRequestBusses = raRequestBusses;
        this.raCompanyBussinesses = raCompanyBussinesses;
    }

   
    // Property accessors

    public Integer getBuisnessTypeId() {
        return this.buisnessTypeId;
    }
    
    public void setBuisnessTypeId(Integer buisnessTypeId) {
        this.buisnessTypeId = buisnessTypeId;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public String getBussStatus() {
        return this.bussStatus;
    }
    
    public void setBussStatus(String bussStatus) {
        this.bussStatus = bussStatus;
    }

    public String getBuisnessType() {
        return this.buisnessType;
    }
    
    public void setBuisnessType(String buisnessType) {
        this.buisnessType = buisnessType;
    }

    public Set getRaBussSupplyProds() {
        return this.raBussSupplyProds;
    }
    
    public void setRaBussSupplyProds(Set raBussSupplyProds) {
        this.raBussSupplyProds = raBussSupplyProds;
    }

    public Set getRaRequestBusses() {
        return this.raRequestBusses;
    }
    
    public void setRaRequestBusses(Set raRequestBusses) {
        this.raRequestBusses = raRequestBusses;
    }

    public Set getRaCompanyBussinesses() {
        return this.raCompanyBussinesses;
    }
    
    public void setRaCompanyBussinesses(Set raCompanyBussinesses) {
        this.raCompanyBussinesses = raCompanyBussinesses;
    }

	public Integer[] getCompanyBussiness() {
		return companyBussiness;
	}

	public void setCompanyBussiness(Integer[] companyBussiness) {
		this.companyBussiness = companyBussiness;
	}
   








}