package com.kjnext.hibernate;



/**
 * RaBussCategory generated by MyEclipse - Hibernate Tools
 */

public class RaBussCategory  implements java.io.Serializable {


    // Fields    

     private RaBussCategoryId id;


    // Constructors

    /** default constructor */
    public RaBussCategory() {
    }

    
    /** full constructor */
    public RaBussCategory(RaBussCategoryId id) {
        this.id = id;
    }

   
    // Property accessors

    public RaBussCategoryId getId() {
        return this.id;
    }
    
    public void setId(RaBussCategoryId id) {
        this.id = id;
    }
   








}