package com.kjnext.hibernate;



/**
 * RaBussCategoryId generated by MyEclipse - Hibernate Tools
 */

public class RaBussCategoryId  implements java.io.Serializable {


    // Fields    

     private Integer bussCatId;
     private String description;


    // Constructors

    /** default constructor */
    public RaBussCategoryId() {
    }

	/** minimal constructor */
    public RaBussCategoryId(Integer bussCatId) {
        this.bussCatId = bussCatId;
    }
    
    /** full constructor */
    public RaBussCategoryId(Integer bussCatId, String description) {
        this.bussCatId = bussCatId;
        this.description = description;
    }

   
    // Property accessors

    public Integer getBussCatId() {
        return this.bussCatId;
    }
    
    public void setBussCatId(Integer bussCatId) {
        this.bussCatId = bussCatId;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RaBussCategoryId) ) return false;
		 RaBussCategoryId castOther = ( RaBussCategoryId ) other; 
         
		 return ( (this.getBussCatId()==castOther.getBussCatId()) || ( this.getBussCatId()!=null && castOther.getBussCatId()!=null && this.getBussCatId().equals(castOther.getBussCatId()) ) )
 && ( (this.getDescription()==castOther.getDescription()) || ( this.getDescription()!=null && castOther.getDescription()!=null && this.getDescription().equals(castOther.getDescription()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getBussCatId() == null ? 0 : this.getBussCatId().hashCode() );
         result = 37 * result + ( getDescription() == null ? 0 : this.getDescription().hashCode() );
         return result;
   }   





}