package com.kjnext.hibernate;



/**
 * RaBussSupplyProdId generated by MyEclipse - Hibernate Tools
 */

public class RaBussSupplyProdId  implements java.io.Serializable {


    // Fields    

     private Integer bussCatId;
     private RaBussinessTypeMaster raBussinessTypeMaster;


    // Constructors

    /** default constructor */
    public RaBussSupplyProdId() {
    }

	/** minimal constructor */
    public RaBussSupplyProdId(Integer bussCatId) {
        this.bussCatId = bussCatId;
    }
    
    /** full constructor */
    public RaBussSupplyProdId(Integer bussCatId, RaBussinessTypeMaster raBussinessTypeMaster) {
        this.bussCatId = bussCatId;
        this.raBussinessTypeMaster = raBussinessTypeMaster;
    }

   
    // Property accessors

    public Integer getBussCatId() {
        return this.bussCatId;
    }
    
    public void setBussCatId(Integer bussCatId) {
        this.bussCatId = bussCatId;
    }

    public RaBussinessTypeMaster getRaBussinessTypeMaster() {
        return this.raBussinessTypeMaster;
    }
    
    public void setRaBussinessTypeMaster(RaBussinessTypeMaster raBussinessTypeMaster) {
        this.raBussinessTypeMaster = raBussinessTypeMaster;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RaBussSupplyProdId) ) return false;
		 RaBussSupplyProdId castOther = ( RaBussSupplyProdId ) other; 
         
		 return ( (this.getBussCatId()==castOther.getBussCatId()) || ( this.getBussCatId()!=null && castOther.getBussCatId()!=null && this.getBussCatId().equals(castOther.getBussCatId()) ) )
 && ( (this.getRaBussinessTypeMaster()==castOther.getRaBussinessTypeMaster()) || ( this.getRaBussinessTypeMaster()!=null && castOther.getRaBussinessTypeMaster()!=null && this.getRaBussinessTypeMaster().equals(castOther.getRaBussinessTypeMaster()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getBussCatId() == null ? 0 : this.getBussCatId().hashCode() );
         result = 37 * result + ( getRaBussinessTypeMaster() == null ? 0 : this.getRaBussinessTypeMaster().hashCode() );
         return result;
   }   





}