package com.kjnext.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * RaCerProdForm generated by MyEclipse - Hibernate Tools
 */

public class RaCerProdForm  implements java.io.Serializable {


    // Fields    

     private Integer cerProductId;
     private String description;
     private Set raCompanyCerProds = new HashSet(0);


    // Constructors

    /** default constructor */
    public RaCerProdForm() {
    }

	/** minimal constructor */
    public RaCerProdForm(Integer cerProductId) {
        this.cerProductId = cerProductId;
    }
    
    /** full constructor */
    public RaCerProdForm(Integer cerProductId, String description, Set raCompanyCerProds) {
        this.cerProductId = cerProductId;
        this.description = description;
        this.raCompanyCerProds = raCompanyCerProds;
    }

   
    // Property accessors

    public Integer getCerProductId() {
        return this.cerProductId;
    }
    
    public void setCerProductId(Integer cerProductId) {
        this.cerProductId = cerProductId;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public Set getRaCompanyCerProds() {
        return this.raCompanyCerProds;
    }
    
    public void setRaCompanyCerProds(Set raCompanyCerProds) {
        this.raCompanyCerProds = raCompanyCerProds;
    }
   








}