package com.kjnext.hibernate;



/**
 * RaCompanyBussinessId generated by MyEclipse - Hibernate Tools
 */

public class RaCompanyBussinessId  implements java.io.Serializable {


    // Fields    

     private RaCompanyMaster raCompanyMaster;
     private RaBussinessTypeMaster raBussinessTypeMaster;


    // Constructors

    /** default constructor */
    public RaCompanyBussinessId() {
    }

    
    /** full constructor */
    public RaCompanyBussinessId(RaCompanyMaster raCompanyMaster, RaBussinessTypeMaster raBussinessTypeMaster) {
        this.raCompanyMaster = raCompanyMaster;
        this.raBussinessTypeMaster = raBussinessTypeMaster;
    }

   
    // Property accessors

    public RaCompanyMaster getRaCompanyMaster() {
        return this.raCompanyMaster;
    }
    
    public void setRaCompanyMaster(RaCompanyMaster raCompanyMaster) {
        this.raCompanyMaster = raCompanyMaster;
    }

    public RaBussinessTypeMaster getRaBussinessTypeMaster() {
        return this.raBussinessTypeMaster;
    }
    
    public void setRaBussinessTypeMaster(RaBussinessTypeMaster raBussinessTypeMaster) {
        this.raBussinessTypeMaster = raBussinessTypeMaster;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RaCompanyBussinessId) ) return false;
		 RaCompanyBussinessId castOther = ( RaCompanyBussinessId ) other; 
         
		 return ( (this.getRaCompanyMaster()==castOther.getRaCompanyMaster()) || ( this.getRaCompanyMaster()!=null && castOther.getRaCompanyMaster()!=null && this.getRaCompanyMaster().equals(castOther.getRaCompanyMaster()) ) )
 && ( (this.getRaBussinessTypeMaster()==castOther.getRaBussinessTypeMaster()) || ( this.getRaBussinessTypeMaster()!=null && castOther.getRaBussinessTypeMaster()!=null && this.getRaBussinessTypeMaster().equals(castOther.getRaBussinessTypeMaster()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRaCompanyMaster() == null ? 0 : this.getRaCompanyMaster().hashCode() );
         result = 37 * result + ( getRaBussinessTypeMaster() == null ? 0 : this.getRaBussinessTypeMaster().hashCode() );
         return result;
   }   





}