package com.kjnext.hibernate;



/**
 * RaCompanyProduct generated by MyEclipse - Hibernate Tools
 */

public class RaCompanyProduct  implements java.io.Serializable {


    // Fields    

     private RaCompanyProductId id;


    // Constructors

    /** default constructor */
    public RaCompanyProduct() {
    }

    
    /** full constructor */
    public RaCompanyProduct(RaCompanyProductId id) {
        this.id = id;
    }

   
    // Property accessors

    public RaCompanyProductId getId() {
        return this.id;
    }
    
    public void setId(RaCompanyProductId id) {
        this.id = id;
    }
   








}