package com.kjnext.hibernate;



/**
 * RaCompanyBussiness generated by MyEclipse - Hibernate Tools
 */

public class RaCompanyBussiness  implements java.io.Serializable {


    // Fields    

     private RaCompanyBussinessId id;


    // Constructors

    /** default constructor */
    public RaCompanyBussiness() {
    }

    
    /** full constructor */
    public RaCompanyBussiness(RaCompanyBussinessId id) {
        this.id = id;
    }

   
    // Property accessors

    public RaCompanyBussinessId getId() {
        return this.id;
    }
    
    public void setId(RaCompanyBussinessId id) {
        this.id = id;
    }
   








}