package com.kjnext.hibernate;



/**
 * RaCompanyBrand generated by MyEclipse - Hibernate Tools
 */

public class RaCompanyBrand  implements java.io.Serializable {


    // Fields    

     private Integer brandId;
     private String brandName;
     private Integer companyId;


    // Constructors

    /** default constructor */
    public RaCompanyBrand() {
    }

	/** minimal constructor */
    public RaCompanyBrand(Integer brandId) {
        this.brandId = brandId;
    }
    
    /** full constructor */
    public RaCompanyBrand(Integer brandId, String brandName, Integer companyId) {
        this.brandId = brandId;
        this.brandName = brandName;
        this.companyId = companyId;
    }

   
    // Property accessors

    public Integer getBrandId() {
        return this.brandId;
    }
    
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    public String getBrandName() {
        return this.brandName;
    }
    
    public void setBrandName(String brandName) {
        this.brandName = brandName;
    }

    public Integer getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }
   








}