package com.kjnext.hibernate;



/**
 * RaCompanyCerProd generated by MyEclipse - Hibernate Tools
 */

public class RaCompanyCerProd  implements java.io.Serializable {


    // Fields    

     private RaCompanyCerProdId id;


    // Constructors

    /** default constructor */
    public RaCompanyCerProd() {
    }

    
    /** full constructor */
    public RaCompanyCerProd(RaCompanyCerProdId id) {
        this.id = id;
    }

   
    // Property accessors

    public RaCompanyCerProdId getId() {
        return this.id;
    }
    
    public void setId(RaCompanyCerProdId id) {
        this.id = id;
    }
   








}