package com.kjnext.hibernate;



/**
 * RaCompanyCerProdId generated by MyEclipse - Hibernate Tools
 */

public class RaCompanyCerProdId  implements java.io.Serializable {


    // Fields    

     private RaCerProdForm raCerProdForm;
     private RaCompanyMaster raCompanyMaster;


    // Constructors

    /** default constructor */
    public RaCompanyCerProdId() {
    }

    
    /** full constructor */
    public RaCompanyCerProdId(RaCerProdForm raCerProdForm, RaCompanyMaster raCompanyMaster) {
        this.raCerProdForm = raCerProdForm;
        this.raCompanyMaster = raCompanyMaster;
    }

   
    // Property accessors

    public RaCerProdForm getRaCerProdForm() {
        return this.raCerProdForm;
    }
    
    public void setRaCerProdForm(RaCerProdForm raCerProdForm) {
        this.raCerProdForm = raCerProdForm;
    }

    public RaCompanyMaster getRaCompanyMaster() {
        return this.raCompanyMaster;
    }
    
    public void setRaCompanyMaster(RaCompanyMaster raCompanyMaster) {
        this.raCompanyMaster = raCompanyMaster;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RaCompanyCerProdId) ) return false;
		 RaCompanyCerProdId castOther = ( RaCompanyCerProdId ) other; 
         
		 return ( (this.getRaCerProdForm()==castOther.getRaCerProdForm()) || ( this.getRaCerProdForm()!=null && castOther.getRaCerProdForm()!=null && this.getRaCerProdForm().equals(castOther.getRaCerProdForm()) ) )
 && ( (this.getRaCompanyMaster()==castOther.getRaCompanyMaster()) || ( this.getRaCompanyMaster()!=null && castOther.getRaCompanyMaster()!=null && this.getRaCompanyMaster().equals(castOther.getRaCompanyMaster()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRaCerProdForm() == null ? 0 : this.getRaCerProdForm().hashCode() );
         result = 37 * result + ( getRaCompanyMaster() == null ? 0 : this.getRaCompanyMaster().hashCode() );
         return result;
   }   





}