package com.kjnext.hibernate;



/**
 * RaCompanyBussSupply generated by MyEclipse - Hibernate Tools
 */

public class RaCompanyBussSupply  implements java.io.Serializable {


    // Fields    

     private RaCompanyBussSupplyId id;


    // Constructors

    /** default constructor */
    public RaCompanyBussSupply() {
    }

    
    /** full constructor */
    public RaCompanyBussSupply(RaCompanyBussSupplyId id) {
        this.id = id;
    }

   
    // Property accessors

    public RaCompanyBussSupplyId getId() {
        return this.id;
    }
    
    public void setId(RaCompanyBussSupplyId id) {
        this.id = id;
    }
   








}