package com.kjnext.hibernate;



/**
 * RaCompanyOutlet generated by MyEclipse - Hibernate Tools
 */

public class RaCompanyOutlet  implements java.io.Serializable {


    // Fields    

     private RaCompanyOutletId id;


    // Constructors

    /** default constructor */
    public RaCompanyOutlet() {
    }

    
    /** full constructor */
    public RaCompanyOutlet(RaCompanyOutletId id) {
        this.id = id;
    }

   
    // Property accessors

    public RaCompanyOutletId getId() {
        return this.id;
    }
    
    public void setId(RaCompanyOutletId id) {
        this.id = id;
    }
   








}