package com.kjnext.hibernate;



/**
 * RaCompanyProductId generated by MyEclipse - Hibernate Tools
 */

public class RaCompanyProductId  implements java.io.Serializable {


    // Fields    

     public RaCompanyMaster raCompanyMaster;
     public RaProductMaster raProductMaster;


    // Constructors

    /** default constructor */
    public RaCompanyProductId() {
    }

    
    /** full constructor */
    public RaCompanyProductId(RaCompanyMaster raCompanyMaster, RaProductMaster raProductMaster) {
        this.raCompanyMaster = raCompanyMaster;
        this.raProductMaster = raProductMaster;
    }

   
    // Property accessors

    public RaCompanyMaster getRaCompanyMaster() {
        return this.raCompanyMaster;
    }
    
    public void setRaCompanyMaster(RaCompanyMaster raCompanyMaster) {
        this.raCompanyMaster = raCompanyMaster;
    }

    public RaProductMaster getRaProductMaster() {
        return this.raProductMaster;
    }
    
    public void setRaProductMaster(RaProductMaster raProductMaster) {
        this.raProductMaster = raProductMaster;
    }
    public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RaCompanyProductId) ) return false;
		 RaCompanyProductId castOther = ( RaCompanyProductId ) other; 
         
		 return ( (this.getRaCompanyMaster()==castOther.getRaCompanyMaster()) || ( this.getRaCompanyMaster()!=null && castOther.getRaCompanyMaster()!=null && this.getRaCompanyMaster().equals(castOther.getRaCompanyMaster()) ) )
 && ( (this.getRaProductMaster()==castOther.getRaProductMaster()) || ( this.getRaProductMaster()!=null && castOther.getRaProductMaster()!=null && this.getRaProductMaster().equals(castOther.getRaProductMaster()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRaCompanyMaster() == null ? 0 : this.getRaCompanyMaster().hashCode() );
         result = 37 * result + ( getRaProductMaster() == null ? 0 : this.getRaProductMaster().hashCode() );
         return result;
   }   

}