package com.kjnext.hibernate;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * RaCompanyMaster generated by MyEclipse - Hibernate Tools
 */

public class RaCompanyMaster  implements java.io.Serializable {


    // Fields    

     private Integer companyId;
     private String companyName;
     private String companyHolding;
     private Date createDate;
     private String companyStatus;
     private Date modifyDate;
     private String priFname;
     private Integer maxUsers;
     private String priLname;
     private String priPosition;
     private String priOffaddress;
     private String priCity;
     private String priDistrict;
     private String priZip;
     private Integer priStateId;
     private String priPhone;
     private String priFax;
     private String priEmail;
     private String priUrl1;
     private String priUrl2;
     private String srFname;
     private String srLname;
     private String srPosition;
     private String srAddress;
     private String srCity;
     private String srDistrict;
     private String srZip;
     private Integer srStateId;
     private String srPhone;
     private String srFax;
     private String srEmail;
     private String comments;
     private String raCertifiedProd;
     private String prodFuture;
     private Date prodFutureDate;
     private String salePurchaseRaProd;
     private String salePurchaseRaFuture;
     private Date salePurchaseRaFutureDate;
     private Integer totOutlet;
     private Integer totOutletRa;
     private Integer annualSale;
     private String raSeal;
     private String raSealAdvt;
     private String raMembership;
     private String salePurchaseBrand;
     private String raCertifiedProdSupply;
     private String otherBussinessType;
     private String otherBussProduct;
     private String otherExpSaleProduct;
     private String otherImpSupplyProduct;
     private String raSupplyProd;
     private String logoFphoto;
     private String logoSphoto;
     private String logoTphoto;
     private String sealComments;
     private String otherProduct;
     private String raProdBrand1;
     private String raProdBrand2;
     private String raProdBrand3;
     private String raProdBrand4;
     private String newlMemFname;
     private String newlMemFlname;
     private String newlMemFtitle;
     private String newlMemFemail;
     private String newlMemSname;
     private String newlMemSlname;
     private String newlMemStitle;
     private String newlMemSemail;
     private String newlMemTname;
     private String newlMemTlname;
     private String newlMemTtitle;
     private String newlMemTemail;
     private String raUserAgreement;
     private String raPrivacyPolicy;
     private String otherProdForm;
     private String scaaScoring;
     private String cupProfile;
     private String custPhone;
     private String agreementStatus;
     private Set raUserMasters = new HashSet(0);
     private Set raCompanyCerProds = new HashSet(0);
     private Set raCompanyOutlets = new HashSet(0);
     private Set raCompanyBussinesses = new HashSet(0);
     private Set raCompanyBussSupplies = new HashSet(0);
     private Set raCompanyStates = new HashSet(0);
     private Set raTraceOfferses = new HashSet(0);
     private Set raCompanyProducts = new HashSet(0);
     private String passWord;

    // Constructors

  

	/** default constructor */
    public RaCompanyMaster() {
    }

	/** minimal constructor */
    public RaCompanyMaster(Integer companyId, String companyName, Date createDate, String companyStatus) {
        this.companyId = companyId;
        this.companyName = companyName;
        this.createDate = createDate;
        this.companyStatus = companyStatus;
    }
    
    /** full constructor */
    public RaCompanyMaster(Integer companyId, String companyName, String companyHolding, Date createDate, String companyStatus, Date modifyDate, String priFname, Integer maxUsers, String priLname, String priPosition, String priOffaddress, String priCity, String priDistrict, String priZip, Integer priStateId, String priPhone, String priFax, String priEmail, String priUrl1, String priUrl2, String srFname, String srLname, String srPosition, String srAddress, String srCity, String srDistrict, String srZip, Integer srStateId, String srPhone, String srFax, String srEmail, String comments, String raCertifiedProd, String prodFuture, Date prodFutureDate, String salePurchaseRaProd, String salePurchaseRaFuture, Date salePurchaseRaFutureDate, Integer totOutlet, Integer totOutletRa, Integer annualSale, String raSeal, String raSealAdvt, String raMembership, String salePurchaseBrand, String raCertifiedProdSupply, String otherBussinessType, String otherBussProduct, String otherExpSaleProduct, String otherImpSupplyProduct, String raSupplyProd, String logoFphoto, String logoSphoto, String logoTphoto, String sealComments, String otherProduct, String raProdBrand1, String raProdBrand2, String raProdBrand3, String raProdBrand4, String newlMemFname, String newlMemFlname, String newlMemFtitle, String newlMemFemail, String newlMemSname, String newlMemSlname, String newlMemStitle, String newlMemSemail, String newlMemTname, String newlMemTlname, String newlMemTtitle, String newlMemTemail, String raUserAgreement, String raPrivacyPolicy, String otherProdForm, String scaaScoring, String cupProfile, String custPhone, String agreementStatus, Set raUserMasters, Set raCompanyCerProds, Set raCompanyOutlets, Set raCompanyBussinesses, Set raCompanyBussSupplies, Set raCompanyStates, Set raTraceOfferses, Set raCompanyProducts) {
        this.companyId = companyId;
        this.companyName = companyName;
        this.companyHolding = companyHolding;
        this.createDate = createDate;
        this.companyStatus = companyStatus;
        this.modifyDate = modifyDate;
        this.priFname = priFname;
        this.maxUsers = maxUsers;
        this.priLname = priLname;
        this.priPosition = priPosition;
        this.priOffaddress = priOffaddress;
        this.priCity = priCity;
        this.priDistrict = priDistrict;
        this.priZip = priZip;
        this.priStateId = priStateId;
        this.priPhone = priPhone;
        this.priFax = priFax;
        this.priEmail = priEmail;
        this.priUrl1 = priUrl1;
        this.priUrl2 = priUrl2;
        this.srFname = srFname;
        this.srLname = srLname;
        this.srPosition = srPosition;
        this.srAddress = srAddress;
        this.srCity = srCity;
        this.srDistrict = srDistrict;
        this.srZip = srZip;
        this.srStateId = srStateId;
        this.srPhone = srPhone;
        this.srFax = srFax;
        this.srEmail = srEmail;
        this.comments = comments;
        this.raCertifiedProd = raCertifiedProd;
        this.prodFuture = prodFuture;
        this.prodFutureDate = prodFutureDate;
        this.salePurchaseRaProd = salePurchaseRaProd;
        this.salePurchaseRaFuture = salePurchaseRaFuture;
        this.salePurchaseRaFutureDate = salePurchaseRaFutureDate;
        this.totOutlet = totOutlet;
        this.totOutletRa = totOutletRa;
        this.annualSale = annualSale;
        this.raSeal = raSeal;
        this.raSealAdvt = raSealAdvt;
        this.raMembership = raMembership;
        this.salePurchaseBrand = salePurchaseBrand;
        this.raCertifiedProdSupply = raCertifiedProdSupply;
        this.otherBussinessType = otherBussinessType;
        this.otherBussProduct = otherBussProduct;
        this.otherExpSaleProduct = otherExpSaleProduct;
        this.otherImpSupplyProduct = otherImpSupplyProduct;
        this.raSupplyProd = raSupplyProd;
        this.logoFphoto = logoFphoto;
        this.logoSphoto = logoSphoto;
        this.logoTphoto = logoTphoto;
        this.sealComments = sealComments;
        this.otherProduct = otherProduct;
        this.raProdBrand1 = raProdBrand1;
        this.raProdBrand2 = raProdBrand2;
        this.raProdBrand3 = raProdBrand3;
        this.raProdBrand4 = raProdBrand4;
        this.newlMemFname = newlMemFname;
        this.newlMemFlname = newlMemFlname;
        this.newlMemFtitle = newlMemFtitle;
        this.newlMemFemail = newlMemFemail;
        this.newlMemSname = newlMemSname;
        this.newlMemSlname = newlMemSlname;
        this.newlMemStitle = newlMemStitle;
        this.newlMemSemail = newlMemSemail;
        this.newlMemTname = newlMemTname;
        this.newlMemTlname = newlMemTlname;
        this.newlMemTtitle = newlMemTtitle;
        this.newlMemTemail = newlMemTemail;
        this.raUserAgreement = raUserAgreement;
        this.raPrivacyPolicy = raPrivacyPolicy;
        this.otherProdForm = otherProdForm;
        this.scaaScoring = scaaScoring;
        this.cupProfile = cupProfile;
        this.custPhone = custPhone;
        this.agreementStatus = agreementStatus;
        this.raUserMasters = raUserMasters;
        this.raCompanyCerProds = raCompanyCerProds;
        this.raCompanyOutlets = raCompanyOutlets;
        this.raCompanyBussinesses = raCompanyBussinesses;
        this.raCompanyBussSupplies = raCompanyBussSupplies;
        this.raCompanyStates = raCompanyStates;
        this.raTraceOfferses = raTraceOfferses;
        this.raCompanyProducts = raCompanyProducts;
    }

   
    // Property accessors

    public Integer getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    public String getCompanyHolding() {
        return this.companyHolding;
    }
    
    public void setCompanyHolding(String companyHolding) {
        this.companyHolding = companyHolding;
    }

    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public String getCompanyStatus() {
        return this.companyStatus;
    }
    
    public void setCompanyStatus(String companyStatus) {
        this.companyStatus = companyStatus;
    }

    public Date getModifyDate() {
        return this.modifyDate;
    }
    
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    public String getPriFname() {
        return this.priFname;
    }
    
    public void setPriFname(String priFname) {
        this.priFname = priFname;
    }

    public Integer getMaxUsers() {
        return this.maxUsers;
    }
    
    public void setMaxUsers(Integer maxUsers) {
        this.maxUsers = maxUsers;
    }

    public String getPriLname() {
        return this.priLname;
    }
    
    public void setPriLname(String priLname) {
        this.priLname = priLname;
    }

    public String getPriPosition() {
        return this.priPosition;
    }
    
    public void setPriPosition(String priPosition) {
        this.priPosition = priPosition;
    }

    public String getPriOffaddress() {
        return this.priOffaddress;
    }
    
    public void setPriOffaddress(String priOffaddress) {
        this.priOffaddress = priOffaddress;
    }

    public String getPriCity() {
        return this.priCity;
    }
    
    public void setPriCity(String priCity) {
        this.priCity = priCity;
    }

    public String getPriDistrict() {
        return this.priDistrict;
    }
    
    public void setPriDistrict(String priDistrict) {
        this.priDistrict = priDistrict;
    }

    public String getPriZip() {
        return this.priZip;
    }
    
    public void setPriZip(String priZip) {
        this.priZip = priZip;
    }

    public Integer getPriStateId() {
        return this.priStateId;
    }
    
    public void setPriStateId(Integer priStateId) {
        this.priStateId = priStateId;
    }

    public String getPriPhone() {
        return this.priPhone;
    }
    
    public void setPriPhone(String priPhone) {
        this.priPhone = priPhone;
    }

    public String getPriFax() {
        return this.priFax;
    }
    
    public void setPriFax(String priFax) {
        this.priFax = priFax;
    }

    public String getPriEmail() {
        return this.priEmail;
    }
    
    public void setPriEmail(String priEmail) {
        this.priEmail = priEmail;
    }

    public String getPriUrl1() {
        return this.priUrl1;
    }
    
    public void setPriUrl1(String priUrl1) {
        this.priUrl1 = priUrl1;
    }

    public String getPriUrl2() {
        return this.priUrl2;
    }
    
    public void setPriUrl2(String priUrl2) {
        this.priUrl2 = priUrl2;
    }

    public String getSrFname() {
        return this.srFname;
    }
    
    public void setSrFname(String srFname) {
        this.srFname = srFname;
    }

    public String getSrLname() {
        return this.srLname;
    }
    
    public void setSrLname(String srLname) {
        this.srLname = srLname;
    }

    public String getSrPosition() {
        return this.srPosition;
    }
    
    public void setSrPosition(String srPosition) {
        this.srPosition = srPosition;
    }

    public String getSrAddress() {
        return this.srAddress;
    }
    
    public void setSrAddress(String srAddress) {
        this.srAddress = srAddress;
    }

    public String getSrCity() {
        return this.srCity;
    }
    
    public void setSrCity(String srCity) {
        this.srCity = srCity;
    }

    public String getSrDistrict() {
        return this.srDistrict;
    }
    
    public void setSrDistrict(String srDistrict) {
        this.srDistrict = srDistrict;
    }

    public String getSrZip() {
        return this.srZip;
    }
    
    public void setSrZip(String srZip) {
        this.srZip = srZip;
    }

    public Integer getSrStateId() {
        return this.srStateId;
    }
    
    public void setSrStateId(Integer srStateId) {
        this.srStateId = srStateId;
    }

    public String getSrPhone() {
        return this.srPhone;
    }
    
    public void setSrPhone(String srPhone) {
        this.srPhone = srPhone;
    }

    public String getSrFax() {
        return this.srFax;
    }
    
    public void setSrFax(String srFax) {
        this.srFax = srFax;
    }

    public String getSrEmail() {
        return this.srEmail;
    }
    
    public void setSrEmail(String srEmail) {
        this.srEmail = srEmail;
    }

    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }

    public String getRaCertifiedProd() {
        return this.raCertifiedProd;
    }
    
    public void setRaCertifiedProd(String raCertifiedProd) {
        this.raCertifiedProd = raCertifiedProd;
    }

    public String getProdFuture() {
        return this.prodFuture;
    }
    
    public void setProdFuture(String prodFuture) {
        this.prodFuture = prodFuture;
    }

    public Date getProdFutureDate() {
        return this.prodFutureDate;
    }
    
    public void setProdFutureDate(Date prodFutureDate) {
        this.prodFutureDate = prodFutureDate;
    }

    public String getSalePurchaseRaProd() {
        return this.salePurchaseRaProd;
    }
    
    public void setSalePurchaseRaProd(String salePurchaseRaProd) {
        this.salePurchaseRaProd = salePurchaseRaProd;
    }

    public String getSalePurchaseRaFuture() {
        return this.salePurchaseRaFuture;
    }
    
    public void setSalePurchaseRaFuture(String salePurchaseRaFuture) {
        this.salePurchaseRaFuture = salePurchaseRaFuture;
    }

    public Date getSalePurchaseRaFutureDate() {
        return this.salePurchaseRaFutureDate;
    }
    
    public void setSalePurchaseRaFutureDate(Date salePurchaseRaFutureDate) {
        this.salePurchaseRaFutureDate = salePurchaseRaFutureDate;
    }

    public Integer getTotOutlet() {
        return this.totOutlet;
    }
    
    public void setTotOutlet(Integer totOutlet) {
        this.totOutlet = totOutlet;
    }

    public Integer getTotOutletRa() {
        return this.totOutletRa;
    }
    
    public void setTotOutletRa(Integer totOutletRa) {
        this.totOutletRa = totOutletRa;
    }

    public Integer getAnnualSale() {
        return this.annualSale;
    }
    
    public void setAnnualSale(Integer annualSale) {
        this.annualSale = annualSale;
    }

    public String getRaSeal() {
        return this.raSeal;
    }
    
    public void setRaSeal(String raSeal) {
        this.raSeal = raSeal;
    }

    public String getRaSealAdvt() {
        return this.raSealAdvt;
    }
    
    public void setRaSealAdvt(String raSealAdvt) {
        this.raSealAdvt = raSealAdvt;
    }

    public String getRaMembership() {
        return this.raMembership;
    }
    
    public void setRaMembership(String raMembership) {
        this.raMembership = raMembership;
    }

    public String getSalePurchaseBrand() {
        return this.salePurchaseBrand;
    }
    
    public void setSalePurchaseBrand(String salePurchaseBrand) {
        this.salePurchaseBrand = salePurchaseBrand;
    }

    public String getRaCertifiedProdSupply() {
        return this.raCertifiedProdSupply;
    }
    
    public void setRaCertifiedProdSupply(String raCertifiedProdSupply) {
        this.raCertifiedProdSupply = raCertifiedProdSupply;
    }

    public String getOtherBussinessType() {
        return this.otherBussinessType;
    }
    
    public void setOtherBussinessType(String otherBussinessType) {
        this.otherBussinessType = otherBussinessType;
    }

    public String getOtherBussProduct() {
        return this.otherBussProduct;
    }
    
    public void setOtherBussProduct(String otherBussProduct) {
        this.otherBussProduct = otherBussProduct;
    }

    public String getOtherExpSaleProduct() {
        return this.otherExpSaleProduct;
    }
    
    public void setOtherExpSaleProduct(String otherExpSaleProduct) {
        this.otherExpSaleProduct = otherExpSaleProduct;
    }

    public String getOtherImpSupplyProduct() {
        return this.otherImpSupplyProduct;
    }
    
    public void setOtherImpSupplyProduct(String otherImpSupplyProduct) {
        this.otherImpSupplyProduct = otherImpSupplyProduct;
    }

    public String getRaSupplyProd() {
        return this.raSupplyProd;
    }
    
    public void setRaSupplyProd(String raSupplyProd) {
        this.raSupplyProd = raSupplyProd;
    }

    public String getLogoFphoto() {
        return this.logoFphoto;
    }
    
    public void setLogoFphoto(String logoFphoto) {
        this.logoFphoto = logoFphoto;
    }

    public String getLogoSphoto() {
        return this.logoSphoto;
    }
    
    public void setLogoSphoto(String logoSphoto) {
        this.logoSphoto = logoSphoto;
    }

    public String getLogoTphoto() {
        return this.logoTphoto;
    }
    
    public void setLogoTphoto(String logoTphoto) {
        this.logoTphoto = logoTphoto;
    }

    public String getSealComments() {
        return this.sealComments;
    }
    
    public void setSealComments(String sealComments) {
        this.sealComments = sealComments;
    }

    public String getOtherProduct() {
        return this.otherProduct;
    }
    
    public void setOtherProduct(String otherProduct) {
        this.otherProduct = otherProduct;
    }

    public String getRaProdBrand1() {
        return this.raProdBrand1;
    }
    
    public void setRaProdBrand1(String raProdBrand1) {
        this.raProdBrand1 = raProdBrand1;
    }

    public String getRaProdBrand2() {
        return this.raProdBrand2;
    }
    
    public void setRaProdBrand2(String raProdBrand2) {
        this.raProdBrand2 = raProdBrand2;
    }

    public String getRaProdBrand3() {
        return this.raProdBrand3;
    }
    
    public void setRaProdBrand3(String raProdBrand3) {
        this.raProdBrand3 = raProdBrand3;
    }

    public String getRaProdBrand4() {
        return this.raProdBrand4;
    }
    
    public void setRaProdBrand4(String raProdBrand4) {
        this.raProdBrand4 = raProdBrand4;
    }

    public String getNewlMemFname() {
        return this.newlMemFname;
    }
    
    public void setNewlMemFname(String newlMemFname) {
        this.newlMemFname = newlMemFname;
    }

    public String getNewlMemFlname() {
        return this.newlMemFlname;
    }
    
    public void setNewlMemFlname(String newlMemFlname) {
        this.newlMemFlname = newlMemFlname;
    }

    public String getNewlMemFtitle() {
        return this.newlMemFtitle;
    }
    
    public void setNewlMemFtitle(String newlMemFtitle) {
        this.newlMemFtitle = newlMemFtitle;
    }

    public String getNewlMemFemail() {
        return this.newlMemFemail;
    }
    
    public void setNewlMemFemail(String newlMemFemail) {
        this.newlMemFemail = newlMemFemail;
    }

    public String getNewlMemSname() {
        return this.newlMemSname;
    }
    
    public void setNewlMemSname(String newlMemSname) {
        this.newlMemSname = newlMemSname;
    }

    public String getNewlMemSlname() {
        return this.newlMemSlname;
    }
    
    public void setNewlMemSlname(String newlMemSlname) {
        this.newlMemSlname = newlMemSlname;
    }

    public String getNewlMemStitle() {
        return this.newlMemStitle;
    }
    
    public void setNewlMemStitle(String newlMemStitle) {
        this.newlMemStitle = newlMemStitle;
    }

    public String getNewlMemSemail() {
        return this.newlMemSemail;
    }
    
    public void setNewlMemSemail(String newlMemSemail) {
        this.newlMemSemail = newlMemSemail;
    }

    public String getNewlMemTname() {
        return this.newlMemTname;
    }
    
    public void setNewlMemTname(String newlMemTname) {
        this.newlMemTname = newlMemTname;
    }

    public String getNewlMemTlname() {
        return this.newlMemTlname;
    }
    
    public void setNewlMemTlname(String newlMemTlname) {
        this.newlMemTlname = newlMemTlname;
    }

    public String getNewlMemTtitle() {
        return this.newlMemTtitle;
    }
    
    public void setNewlMemTtitle(String newlMemTtitle) {
        this.newlMemTtitle = newlMemTtitle;
    }

    public String getNewlMemTemail() {
        return this.newlMemTemail;
    }
    
    public void setNewlMemTemail(String newlMemTemail) {
        this.newlMemTemail = newlMemTemail;
    }

    public String getRaUserAgreement() {
        return this.raUserAgreement;
    }
    
    public void setRaUserAgreement(String raUserAgreement) {
        this.raUserAgreement = raUserAgreement;
    }

    public String getRaPrivacyPolicy() {
        return this.raPrivacyPolicy;
    }
    
    public void setRaPrivacyPolicy(String raPrivacyPolicy) {
        this.raPrivacyPolicy = raPrivacyPolicy;
    }

    public String getOtherProdForm() {
        return this.otherProdForm;
    }
    
    public void setOtherProdForm(String otherProdForm) {
        this.otherProdForm = otherProdForm;
    }

    public String getScaaScoring() {
        return this.scaaScoring;
    }
    
    public void setScaaScoring(String scaaScoring) {
        this.scaaScoring = scaaScoring;
    }

    public String getCupProfile() {
        return this.cupProfile;
    }
    
    public void setCupProfile(String cupProfile) {
        this.cupProfile = cupProfile;
    }

    public String getCustPhone() {
        return this.custPhone;
    }
    
    public void setCustPhone(String custPhone) {
        this.custPhone = custPhone;
    }

    public String getAgreementStatus() {
        return this.agreementStatus;
    }
    
    public void setAgreementStatus(String agreementStatus) {
        this.agreementStatus = agreementStatus;
    }

    public Set getRaUserMasters() {
        return this.raUserMasters;
    }
    
    public void setRaUserMasters(Set raUserMasters) {
        this.raUserMasters = raUserMasters;
    }

    public Set getRaCompanyCerProds() {
        return this.raCompanyCerProds;
    }
    
    public void setRaCompanyCerProds(Set raCompanyCerProds) {
        this.raCompanyCerProds = raCompanyCerProds;
    }

    public Set getRaCompanyOutlets() {
        return this.raCompanyOutlets;
    }
    
    public void setRaCompanyOutlets(Set raCompanyOutlets) {
        this.raCompanyOutlets = raCompanyOutlets;
    }

    public Set getRaCompanyBussinesses() {
        return this.raCompanyBussinesses;
    }
    
    public void setRaCompanyBussinesses(Set raCompanyBussinesses) {
        this.raCompanyBussinesses = raCompanyBussinesses;
    }

    public Set getRaCompanyBussSupplies() {
        return this.raCompanyBussSupplies;
    }
    
    public void setRaCompanyBussSupplies(Set raCompanyBussSupplies) {
        this.raCompanyBussSupplies = raCompanyBussSupplies;
    }

    public Set getRaCompanyStates() {
        return this.raCompanyStates;
    }
    
    public void setRaCompanyStates(Set raCompanyStates) {
        this.raCompanyStates = raCompanyStates;
    }

    public Set getRaTraceOfferses() {
        return this.raTraceOfferses;
    }
    
    public void setRaTraceOfferses(Set raTraceOfferses) {
        this.raTraceOfferses = raTraceOfferses;
    }

    public Set getRaCompanyProducts() {
        return this.raCompanyProducts;
    }
    
    public void setRaCompanyProducts(Set raCompanyProducts) {
        this.raCompanyProducts = raCompanyProducts;
    }

	public String getPassWord() {
		return passWord;
	}

	public void setPassWord(String passWord) {
		this.passWord = passWord;
	}

	


}