package com.kjnext.hibernate;



/**
 * RaCompanyBussSupplyId generated by MyEclipse - Hibernate Tools
 */

public class RaCompanyBussSupplyId  implements java.io.Serializable {


    // Fields    

     private Integer bussCatId;
     private RaCompanyMaster raCompanyMaster;


    // Constructors

    /** default constructor */
    public RaCompanyBussSupplyId() {
    }

    
    /** full constructor */
    public RaCompanyBussSupplyId(Integer bussCatId, RaCompanyMaster raCompanyMaster) {
        this.bussCatId = bussCatId;
        this.raCompanyMaster = raCompanyMaster;
    }

   
    // Property accessors

    public Integer getBussCatId() {
        return this.bussCatId;
    }
    
    public void setBussCatId(Integer bussCatId) {
        this.bussCatId = bussCatId;
    }

    public RaCompanyMaster getRaCompanyMaster() {
        return this.raCompanyMaster;
    }
    
    public void setRaCompanyMaster(RaCompanyMaster raCompanyMaster) {
        this.raCompanyMaster = raCompanyMaster;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RaCompanyBussSupplyId) ) return false;
		 RaCompanyBussSupplyId castOther = ( RaCompanyBussSupplyId ) other; 
         
		 return ( (this.getBussCatId()==castOther.getBussCatId()) || ( this.getBussCatId()!=null && castOther.getBussCatId()!=null && this.getBussCatId().equals(castOther.getBussCatId()) ) )
 && ( (this.getRaCompanyMaster()==castOther.getRaCompanyMaster()) || ( this.getRaCompanyMaster()!=null && castOther.getRaCompanyMaster()!=null && this.getRaCompanyMaster().equals(castOther.getRaCompanyMaster()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getBussCatId() == null ? 0 : this.getBussCatId().hashCode() );
         result = 37 * result + ( getRaCompanyMaster() == null ? 0 : this.getRaCompanyMaster().hashCode() );
         return result;
   }   





}