package com.kjnext.hibernate;



/**
 * RaCompanyState generated by MyEclipse - Hibernate Tools
 */

public class RaCompanyState  implements java.io.Serializable {


    // Fields    

     private RaCompanyStateId id;


    // Constructors

    /** default constructor */
    public RaCompanyState() {
    }

    
    /** full constructor */
    public RaCompanyState(RaCompanyStateId id) {
        this.id = id;
    }

   
    // Property accessors

    public RaCompanyStateId getId() {
        return this.id;
    }
    
    public void setId(RaCompanyStateId id) {
        this.id = id;
    }
   








}