package com.kjnext.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * RaDestinationPort generated by MyEclipse - Hibernate Tools
 */

public class RaDestinationPort  implements java.io.Serializable {


    // Fields    

     private Integer destPortId;
     private String description;
     private String destPortStatus;
     private String destinationPort;
     private Set raTraceabilities = new HashSet(0);
     private Set raTraceOfferses = new HashSet(0);


    // Constructors

    /** default constructor */
    public RaDestinationPort() {
    }

	/** minimal constructor */
    public RaDestinationPort(Integer destPortId) {
        this.destPortId = destPortId;
    }
    
    /** full constructor */
    public RaDestinationPort(Integer destPortId, String description, String destPortStatus, String destinationPort, Set raTraceabilities, Set raTraceOfferses) {
        this.destPortId = destPortId;
        this.description = description;
        this.destPortStatus = destPortStatus;
        this.destinationPort = destinationPort;
        this.raTraceabilities = raTraceabilities;
        this.raTraceOfferses = raTraceOfferses;
    }

   
    // Property accessors

    public Integer getDestPortId() {
        return this.destPortId;
    }
    
    public void setDestPortId(Integer destPortId) {
        this.destPortId = destPortId;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public String getDestPortStatus() {
        return this.destPortStatus;
    }
    
    public void setDestPortStatus(String destPortStatus) {
        this.destPortStatus = destPortStatus;
    }

    public String getDestinationPort() {
        return this.destinationPort;
    }
    
    public void setDestinationPort(String destinationPort) {
        this.destinationPort = destinationPort;
    }

    public Set getRaTraceabilities() {
        return this.raTraceabilities;
    }
    
    public void setRaTraceabilities(Set raTraceabilities) {
        this.raTraceabilities = raTraceabilities;
    }

    public Set getRaTraceOfferses() {
        return this.raTraceOfferses;
    }
    
    public void setRaTraceOfferses(Set raTraceOfferses) {
        this.raTraceOfferses = raTraceOfferses;
    }
   








}