package com.kjnext.hibernate;

import java.util.Date;


/**
 * RaDifferentialId generated by MyEclipse - Hibernate Tools
 */

public class RaDifferentialId  implements java.io.Serializable {


    // Fields    

     private String priceExchange;
     private String priceContractMon;
     private Date priceEffDate;
     private String diffCurrency;
     private Date diffCreTmstmp;
     private Date diffUpdTmstmp;
     private String priceStatus;
     private String exchangeType;


    // Constructors

    /** default constructor */
    public RaDifferentialId() {
    }

	/** minimal constructor */
    public RaDifferentialId(String priceExchange, String priceContractMon, Date priceEffDate) {
        this.priceExchange = priceExchange;
        this.priceContractMon = priceContractMon;
        this.priceEffDate = priceEffDate;
    }
    
    /** full constructor */
    public RaDifferentialId(String priceExchange, String priceContractMon, Date priceEffDate, String diffCurrency, Date diffCreTmstmp, Date diffUpdTmstmp, String priceStatus, String exchangeType) {
        this.priceExchange = priceExchange;
        this.priceContractMon = priceContractMon;
        this.priceEffDate = priceEffDate;
        this.diffCurrency = diffCurrency;
        this.diffCreTmstmp = diffCreTmstmp;
        this.diffUpdTmstmp = diffUpdTmstmp;
        this.priceStatus = priceStatus;
        this.exchangeType = exchangeType;
    }

   
    // Property accessors

    public String getPriceExchange() {
        return this.priceExchange;
    }
    
    public void setPriceExchange(String priceExchange) {
        this.priceExchange = priceExchange;
    }

    public String getPriceContractMon() {
        return this.priceContractMon;
    }
    
    public void setPriceContractMon(String priceContractMon) {
        this.priceContractMon = priceContractMon;
    }

    public Date getPriceEffDate() {
        return this.priceEffDate;
    }
    
    public void setPriceEffDate(Date priceEffDate) {
        this.priceEffDate = priceEffDate;
    }

    public String getDiffCurrency() {
        return this.diffCurrency;
    }
    
    public void setDiffCurrency(String diffCurrency) {
        this.diffCurrency = diffCurrency;
    }

    public Date getDiffCreTmstmp() {
        return this.diffCreTmstmp;
    }
    
    public void setDiffCreTmstmp(Date diffCreTmstmp) {
        this.diffCreTmstmp = diffCreTmstmp;
    }

    public Date getDiffUpdTmstmp() {
        return this.diffUpdTmstmp;
    }
    
    public void setDiffUpdTmstmp(Date diffUpdTmstmp) {
        this.diffUpdTmstmp = diffUpdTmstmp;
    }

    public String getPriceStatus() {
        return this.priceStatus;
    }
    
    public void setPriceStatus(String priceStatus) {
        this.priceStatus = priceStatus;
    }

    public String getExchangeType() {
        return this.exchangeType;
    }
    
    public void setExchangeType(String exchangeType) {
        this.exchangeType = exchangeType;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RaDifferentialId) ) return false;
		 RaDifferentialId castOther = ( RaDifferentialId ) other; 
         
		 return ( (this.getPriceExchange()==castOther.getPriceExchange()) || ( this.getPriceExchange()!=null && castOther.getPriceExchange()!=null && this.getPriceExchange().equals(castOther.getPriceExchange()) ) )
 && ( (this.getPriceContractMon()==castOther.getPriceContractMon()) || ( this.getPriceContractMon()!=null && castOther.getPriceContractMon()!=null && this.getPriceContractMon().equals(castOther.getPriceContractMon()) ) )
 && ( (this.getPriceEffDate()==castOther.getPriceEffDate()) || ( this.getPriceEffDate()!=null && castOther.getPriceEffDate()!=null && this.getPriceEffDate().equals(castOther.getPriceEffDate()) ) )
 && ( (this.getDiffCurrency()==castOther.getDiffCurrency()) || ( this.getDiffCurrency()!=null && castOther.getDiffCurrency()!=null && this.getDiffCurrency().equals(castOther.getDiffCurrency()) ) )
 && ( (this.getDiffCreTmstmp()==castOther.getDiffCreTmstmp()) || ( this.getDiffCreTmstmp()!=null && castOther.getDiffCreTmstmp()!=null && this.getDiffCreTmstmp().equals(castOther.getDiffCreTmstmp()) ) )
 && ( (this.getDiffUpdTmstmp()==castOther.getDiffUpdTmstmp()) || ( this.getDiffUpdTmstmp()!=null && castOther.getDiffUpdTmstmp()!=null && this.getDiffUpdTmstmp().equals(castOther.getDiffUpdTmstmp()) ) )
 && ( (this.getPriceStatus()==castOther.getPriceStatus()) || ( this.getPriceStatus()!=null && castOther.getPriceStatus()!=null && this.getPriceStatus().equals(castOther.getPriceStatus()) ) )
 && ( (this.getExchangeType()==castOther.getExchangeType()) || ( this.getExchangeType()!=null && castOther.getExchangeType()!=null && this.getExchangeType().equals(castOther.getExchangeType()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPriceExchange() == null ? 0 : this.getPriceExchange().hashCode() );
         result = 37 * result + ( getPriceContractMon() == null ? 0 : this.getPriceContractMon().hashCode() );
         result = 37 * result + ( getPriceEffDate() == null ? 0 : this.getPriceEffDate().hashCode() );
         result = 37 * result + ( getDiffCurrency() == null ? 0 : this.getDiffCurrency().hashCode() );
         result = 37 * result + ( getDiffCreTmstmp() == null ? 0 : this.getDiffCreTmstmp().hashCode() );
         result = 37 * result + ( getDiffUpdTmstmp() == null ? 0 : this.getDiffUpdTmstmp().hashCode() );
         result = 37 * result + ( getPriceStatus() == null ? 0 : this.getPriceStatus().hashCode() );
         result = 37 * result + ( getExchangeType() == null ? 0 : this.getExchangeType().hashCode() );
         return result;
   }   





}