package com.kjnext.hibernate;



/**
 * RaDifferential generated by MyEclipse - Hibernate Tools
 */

public class RaDifferential  implements java.io.Serializable {


    // Fields    

     private RaDifferentialId id;


    // Constructors

    /** default constructor */
    public RaDifferential() {
    }

    
    /** full constructor */
    public RaDifferential(RaDifferentialId id) {
        this.id = id;
    }

   
    // Property accessors

    public RaDifferentialId getId() {
        return this.id;
    }
    
    public void setId(RaDifferentialId id) {
        this.id = id;
    }
   








}