package com.kjnext.hibernate;

/**
 * RaFarmMaster generated by MyEclipse - Hibernate Tools
 */

public class RaFarmMaster implements java.io.Serializable {

	// Fields

	private Integer farmId;

	private String farmName;

	// Constructors

	/** default constructor */
	public RaFarmMaster() {
	}

	/** full constructor */
	public RaFarmMaster(Integer farmId, String farmName) {
		this.farmId = farmId;
		this.farmName = farmName;
	}

	// Property accessors

	public Integer getFarmId() {
		return this.farmId;
	}

	public void setFarmId(Integer farmId) {
		this.farmId = farmId;
	}

	public String getFarmName() {
		return this.farmName;
	}

	public void setFarmName(String farmName) {
		this.farmName = farmName;
	}

}