package com.kjnext.hibernate;

import java.util.Date;


/**
 * RaLicensingAgreementId generated by MyEclipse - Hibernate Tools
 */

public class RaLicensingAgreementId  implements java.io.Serializable {


    // Fields    

     private Integer companyId;
     private String companyName;
     private String jurisdiction;
     private String legalEntity;
     private String address;
     private String fax;
     private Date laExipiryDate;
     private String laStatus;
     private String contactName;
     private Date laStartDate;


    // Constructors

    /** default constructor */
    public RaLicensingAgreementId() {
    }

    
    /** full constructor */
    public RaLicensingAgreementId(Integer companyId, String companyName, String jurisdiction, String legalEntity, String address, String fax, Date laExipiryDate, String laStatus, String contactName, Date laStartDate) {
        this.companyId = companyId;
        this.companyName = companyName;
        this.jurisdiction = jurisdiction;
        this.legalEntity = legalEntity;
        this.address = address;
        this.fax = fax;
        this.laExipiryDate = laExipiryDate;
        this.laStatus = laStatus;
        this.contactName = contactName;
        this.laStartDate = laStartDate;
    }

   
    // Property accessors

    public Integer getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    public String getJurisdiction() {
        return this.jurisdiction;
    }
    
    public void setJurisdiction(String jurisdiction) {
        this.jurisdiction = jurisdiction;
    }

    public String getLegalEntity() {
        return this.legalEntity;
    }
    
    public void setLegalEntity(String legalEntity) {
        this.legalEntity = legalEntity;
    }

    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }

    public Date getLaExipiryDate() {
        return this.laExipiryDate;
    }
    
    public void setLaExipiryDate(Date laExipiryDate) {
        this.laExipiryDate = laExipiryDate;
    }

    public String getLaStatus() {
        return this.laStatus;
    }
    
    public void setLaStatus(String laStatus) {
        this.laStatus = laStatus;
    }

    public String getContactName() {
        return this.contactName;
    }
    
    public void setContactName(String contactName) {
        this.contactName = contactName;
    }

    public Date getLaStartDate() {
        return this.laStartDate;
    }
    
    public void setLaStartDate(Date laStartDate) {
        this.laStartDate = laStartDate;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RaLicensingAgreementId) ) return false;
		 RaLicensingAgreementId castOther = ( RaLicensingAgreementId ) other; 
         
		 return ( (this.getCompanyId()==castOther.getCompanyId()) || ( this.getCompanyId()!=null && castOther.getCompanyId()!=null && this.getCompanyId().equals(castOther.getCompanyId()) ) )
 && ( (this.getCompanyName()==castOther.getCompanyName()) || ( this.getCompanyName()!=null && castOther.getCompanyName()!=null && this.getCompanyName().equals(castOther.getCompanyName()) ) )
 && ( (this.getJurisdiction()==castOther.getJurisdiction()) || ( this.getJurisdiction()!=null && castOther.getJurisdiction()!=null && this.getJurisdiction().equals(castOther.getJurisdiction()) ) )
 && ( (this.getLegalEntity()==castOther.getLegalEntity()) || ( this.getLegalEntity()!=null && castOther.getLegalEntity()!=null && this.getLegalEntity().equals(castOther.getLegalEntity()) ) )
 && ( (this.getAddress()==castOther.getAddress()) || ( this.getAddress()!=null && castOther.getAddress()!=null && this.getAddress().equals(castOther.getAddress()) ) )
 && ( (this.getFax()==castOther.getFax()) || ( this.getFax()!=null && castOther.getFax()!=null && this.getFax().equals(castOther.getFax()) ) )
 && ( (this.getLaExipiryDate()==castOther.getLaExipiryDate()) || ( this.getLaExipiryDate()!=null && castOther.getLaExipiryDate()!=null && this.getLaExipiryDate().equals(castOther.getLaExipiryDate()) ) )
 && ( (this.getLaStatus()==castOther.getLaStatus()) || ( this.getLaStatus()!=null && castOther.getLaStatus()!=null && this.getLaStatus().equals(castOther.getLaStatus()) ) )
 && ( (this.getContactName()==castOther.getContactName()) || ( this.getContactName()!=null && castOther.getContactName()!=null && this.getContactName().equals(castOther.getContactName()) ) )
 && ( (this.getLaStartDate()==castOther.getLaStartDate()) || ( this.getLaStartDate()!=null && castOther.getLaStartDate()!=null && this.getLaStartDate().equals(castOther.getLaStartDate()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCompanyId() == null ? 0 : this.getCompanyId().hashCode() );
         result = 37 * result + ( getCompanyName() == null ? 0 : this.getCompanyName().hashCode() );
         result = 37 * result + ( getJurisdiction() == null ? 0 : this.getJurisdiction().hashCode() );
         result = 37 * result + ( getLegalEntity() == null ? 0 : this.getLegalEntity().hashCode() );
         result = 37 * result + ( getAddress() == null ? 0 : this.getAddress().hashCode() );
         result = 37 * result + ( getFax() == null ? 0 : this.getFax().hashCode() );
         result = 37 * result + ( getLaExipiryDate() == null ? 0 : this.getLaExipiryDate().hashCode() );
         result = 37 * result + ( getLaStatus() == null ? 0 : this.getLaStatus().hashCode() );
         result = 37 * result + ( getContactName() == null ? 0 : this.getContactName().hashCode() );
         result = 37 * result + ( getLaStartDate() == null ? 0 : this.getLaStartDate().hashCode() );
         return result;
   }   





}