package com.kjnext.hibernate;



/**
 * RaLicensingAgreement generated by MyEclipse - Hibernate Tools
 */

public class RaLicensingAgreement  implements java.io.Serializable {


    // Fields    

     private RaLicensingAgreementId id;


    // Constructors

    /** default constructor */
    public RaLicensingAgreement() {
    }

    
    /** full constructor */
    public RaLicensingAgreement(RaLicensingAgreementId id) {
        this.id = id;
    }

   
    // Property accessors

    public RaLicensingAgreementId getId() {
        return this.id;
    }
    
    public void setId(RaLicensingAgreementId id) {
        this.id = id;
    }
   








}