package com.kjnext.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * RaLoadPort generated by MyEclipse - Hibernate Tools
 */

public class RaLoadPort  implements java.io.Serializable {


    // Fields    

     private Integer loadId;
     private RaOriginMaster raOriginMaster;
     private String description;
     private String loadPortStatus;
     private String loadPortType;
     private Set raTraceabilities = new HashSet(0);


    // Constructors

    /** default constructor */
    public RaLoadPort() {
    }

	/** minimal constructor */
    public RaLoadPort(Integer loadId, RaOriginMaster raOriginMaster) {
        this.loadId = loadId;
        this.raOriginMaster = raOriginMaster;
    }
    
    /** full constructor */
    public RaLoadPort(Integer loadId, RaOriginMaster raOriginMaster, String description, String loadPortStatus, String loadPortType, Set raTraceabilities) {
        this.loadId = loadId;
        this.raOriginMaster = raOriginMaster;
        this.description = description;
        this.loadPortStatus = loadPortStatus;
        this.loadPortType = loadPortType;
        this.raTraceabilities = raTraceabilities;
    }

   
    // Property accessors

    public Integer getLoadId() {
        return this.loadId;
    }
    
    public void setLoadId(Integer loadId) {
        this.loadId = loadId;
    }

    public RaOriginMaster getRaOriginMaster() {
        return this.raOriginMaster;
    }
    
    public void setRaOriginMaster(RaOriginMaster raOriginMaster) {
        this.raOriginMaster = raOriginMaster;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public String getLoadPortStatus() {
        return this.loadPortStatus;
    }
    
    public void setLoadPortStatus(String loadPortStatus) {
        this.loadPortStatus = loadPortStatus;
    }

    public String getLoadPortType() {
        return this.loadPortType;
    }
    
    public void setLoadPortType(String loadPortType) {
        this.loadPortType = loadPortType;
    }

    public Set getRaTraceabilities() {
        return this.raTraceabilities;
    }
    
    public void setRaTraceabilities(Set raTraceabilities) {
        this.raTraceabilities = raTraceabilities;
    }
   








}