package com.kjnext.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * RaModuleMaster generated by MyEclipse - Hibernate Tools
 */

public class RaModuleMaster  implements java.io.Serializable {


    // Fields    

     private Integer moduleId;
     private String moduleName;
     private String imageName;
     private Integer imageWidth;
     private String imageLayerWidth;
     private Set raSubModules = new HashSet(0);


    // Constructors

    /** default constructor */
    public RaModuleMaster() {
    }

	/** minimal constructor */
    public RaModuleMaster(Integer moduleId, String moduleName, String imageName, Integer imageWidth, String imageLayerWidth) {
        this.moduleId = moduleId;
        this.moduleName = moduleName;
        this.imageName = imageName;
        this.imageWidth = imageWidth;
        this.imageLayerWidth = imageLayerWidth;
    }
    
    /** full constructor */
    public RaModuleMaster(Integer moduleId, String moduleName, String imageName, Integer imageWidth, String imageLayerWidth, Set raSubModules) {
        this.moduleId = moduleId;
        this.moduleName = moduleName;
        this.imageName = imageName;
        this.imageWidth = imageWidth;
        this.imageLayerWidth = imageLayerWidth;
        this.raSubModules = raSubModules;
    }

   
    // Property accessors

    public Integer getModuleId() {
        return this.moduleId;
    }
    
    public void setModuleId(Integer moduleId) {
        this.moduleId = moduleId;
    }

    public String getModuleName() {
        return this.moduleName;
    }
    
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName;
    }

    public String getImageName() {
        return this.imageName;
    }
    
    public void setImageName(String imageName) {
        this.imageName = imageName;
    }

    public Integer getImageWidth() {
        return this.imageWidth;
    }
    
    public void setImageWidth(Integer imageWidth) {
        this.imageWidth = imageWidth;
    }

    public String getImageLayerWidth() {
        return this.imageLayerWidth;
    }
    
    public void setImageLayerWidth(String imageLayerWidth) {
        this.imageLayerWidth = imageLayerWidth;
    }

    public Set getRaSubModules() {
        return this.raSubModules;
    }
    
    public void setRaSubModules(Set raSubModules) {
        this.raSubModules = raSubModules;
    }
   








}