package com.kjnext.hibernate;



/**
 * RaModuleAccessId generated by MyEclipse - Hibernate Tools
 */

public class RaModuleAccessId  implements java.io.Serializable {


    // Fields    

     private Integer moduleId;
     private String roleShortName;


    // Constructors

    /** default constructor */
    public RaModuleAccessId() {
    }

    
    /** full constructor */
    public RaModuleAccessId(Integer moduleId, String roleShortName) {
        this.moduleId = moduleId;
        this.roleShortName = roleShortName;
    }

   
    // Property accessors

    public Integer getModuleId() {
        return this.moduleId;
    }
    
    public void setModuleId(Integer moduleId) {
        this.moduleId = moduleId;
    }

    public String getRoleShortName() {
        return this.roleShortName;
    }
    
    public void setRoleShortName(String roleShortName) {
        this.roleShortName = roleShortName;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RaModuleAccessId) ) return false;
		 RaModuleAccessId castOther = ( RaModuleAccessId ) other; 
         
		 return ( (this.getModuleId()==castOther.getModuleId()) || ( this.getModuleId()!=null && castOther.getModuleId()!=null && this.getModuleId().equals(castOther.getModuleId()) ) )
 && ( (this.getRoleShortName()==castOther.getRoleShortName()) || ( this.getRoleShortName()!=null && castOther.getRoleShortName()!=null && this.getRoleShortName().equals(castOther.getRoleShortName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getModuleId() == null ? 0 : this.getModuleId().hashCode() );
         result = 37 * result + ( getRoleShortName() == null ? 0 : this.getRoleShortName().hashCode() );
         return result;
   }   





}