package com.kjnext.hibernate;



/**
 * RaModuleAccess generated by MyEclipse - Hibernate Tools
 */

public class RaModuleAccess  implements java.io.Serializable {


    // Fields    

     private RaModuleAccessId id;


    // Constructors

    /** default constructor */
    public RaModuleAccess() {
    }

    
    /** full constructor */
    public RaModuleAccess(RaModuleAccessId id) {
        this.id = id;
    }

   
    // Property accessors

    public RaModuleAccessId getId() {
        return this.id;
    }
    
    public void setId(RaModuleAccessId id) {
        this.id = id;
    }
   








}