package com.kjnext.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * RaOriginMaster generated by MyEclipse - Hibernate Tools
 */

public class RaOriginMaster  implements java.io.Serializable {


    // Fields    

     private Integer originId;
     private String originDispName;
     private String originType;
     private String originStatus;
     private String originBagSize;
     private Set raProdRegions = new HashSet(0);
     private Set raTraceabilities = new HashSet(0);
     private Set raGradeMasters = new HashSet(0);
     private Set raTraceOfferses = new HashSet(0);
     private Set raLoadPorts = new HashSet(0);


    // Constructors

    /** default constructor */
    public RaOriginMaster() {
    }

	/** minimal constructor */
    public RaOriginMaster(Integer originId) {
        this.originId = originId;
    }
    
    /** full constructor */
    public RaOriginMaster(Integer originId, String originDispName, String originType, String originStatus, String originBagSize, Set raProdRegions, Set raTraceabilities, Set raGradeMasters, Set raTraceOfferses, Set raLoadPorts) {
        this.originId = originId;
        this.originDispName = originDispName;
        this.originType = originType;
        this.originStatus = originStatus;
        this.originBagSize = originBagSize;
        this.raProdRegions = raProdRegions;
        this.raTraceabilities = raTraceabilities;
        this.raGradeMasters = raGradeMasters;
        this.raTraceOfferses = raTraceOfferses;
        this.raLoadPorts = raLoadPorts;
    }

   
    // Property accessors

    public Integer getOriginId() {
        return this.originId;
    }
    
    public void setOriginId(Integer originId) {
        this.originId = originId;
    }

    public String getOriginDispName() {
        return this.originDispName;
    }
    
    public void setOriginDispName(String originDispName) {
        this.originDispName = originDispName;
    }

    public String getOriginType() {
        return this.originType;
    }
    
    public void setOriginType(String originType) {
        this.originType = originType;
    }

    public String getOriginStatus() {
        return this.originStatus;
    }
    
    public void setOriginStatus(String originStatus) {
        this.originStatus = originStatus;
    }

    public String getOriginBagSize() {
        return this.originBagSize;
    }
    
    public void setOriginBagSize(String originBagSize) {
        this.originBagSize = originBagSize;
    }

    public Set getRaProdRegions() {
        return this.raProdRegions;
    }
    
    public void setRaProdRegions(Set raProdRegions) {
        this.raProdRegions = raProdRegions;
    }

    public Set getRaTraceabilities() {
        return this.raTraceabilities;
    }
    
    public void setRaTraceabilities(Set raTraceabilities) {
        this.raTraceabilities = raTraceabilities;
    }

    public Set getRaGradeMasters() {
        return this.raGradeMasters;
    }
    
    public void setRaGradeMasters(Set raGradeMasters) {
        this.raGradeMasters = raGradeMasters;
    }

    public Set getRaTraceOfferses() {
        return this.raTraceOfferses;
    }
    
    public void setRaTraceOfferses(Set raTraceOfferses) {
        this.raTraceOfferses = raTraceOfferses;
    }

    public Set getRaLoadPorts() {
        return this.raLoadPorts;
    }
    
    public void setRaLoadPorts(Set raLoadPorts) {
        this.raLoadPorts = raLoadPorts;
    }
   








}