package com.kjnext.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * RaOutletMaster generated by MyEclipse - Hibernate Tools
 */

public class RaOutletMaster  implements java.io.Serializable {


    // Fields    

     private Integer outletTypeId;
     private String description;
     private Set raCompanyOutlets = new HashSet(0);


    // Constructors

    /** default constructor */
    public RaOutletMaster() {
    }

	/** minimal constructor */
    public RaOutletMaster(Integer outletTypeId) {
        this.outletTypeId = outletTypeId;
    }
    
    /** full constructor */
    public RaOutletMaster(Integer outletTypeId, String description, Set raCompanyOutlets) {
        this.outletTypeId = outletTypeId;
        this.description = description;
        this.raCompanyOutlets = raCompanyOutlets;
    }

   
    // Property accessors

    public Integer getOutletTypeId() {
        return this.outletTypeId;
    }
    
    public void setOutletTypeId(Integer outletTypeId) {
        this.outletTypeId = outletTypeId;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public Set getRaCompanyOutlets() {
        return this.raCompanyOutlets;
    }
    
    public void setRaCompanyOutlets(Set raCompanyOutlets) {
        this.raCompanyOutlets = raCompanyOutlets;
    }
   








}