package com.kjnext.hibernate;



/**
 * RaProducerDataUpload generated by MyEclipse - Hibernate Tools
 */

public class RaProducerDataUpload  implements java.io.Serializable {


    // Fields    

     private RaProducerDataUploadId id;
     private RaProducerMaster raProducerMaster;
     
     

    // Constructors

    /** default constructor */
    public RaProducerDataUpload() {
    }

    
    /** full constructor */
    public RaProducerDataUpload(RaProducerMaster raProducerMaster,RaProducerDataUploadId id) {
    	
        
        this.raProducerMaster = raProducerMaster;
        this.id = id;
    }

   
    

	


	public RaProducerDataUploadId getId() {
        return this.id;
    }
    
    public void setId(RaProducerDataUploadId id) {
        this.id = id;
    }

    public RaProducerMaster getRaProducerMaster() {
        return this.raProducerMaster;
    }
    
    public void setRaProducerMaster(RaProducerMaster raProducerMaster) {
        this.raProducerMaster = raProducerMaster;
    }
   








}