package com.kjnext.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * RaPriceBasis generated by MyEclipse - Hibernate Tools
 */

public class RaPriceBasis  implements java.io.Serializable {


    // Fields    

     private Integer prBasisId;
     private String prBasisDspName;
     private String prBasisDesc;
     private Set raTraceabilities = new HashSet(0);


    // Constructors

    /** default constructor */
    public RaPriceBasis() {
    }

	/** minimal constructor */
    public RaPriceBasis(Integer prBasisId) {
        this.prBasisId = prBasisId;
    }
    
    /** full constructor */
    public RaPriceBasis(Integer prBasisId, String prBasisDspName, String prBasisDesc, Set raTraceabilities) {
        this.prBasisId = prBasisId;
        this.prBasisDspName = prBasisDspName;
        this.prBasisDesc = prBasisDesc;
        this.raTraceabilities = raTraceabilities;
    }

   
    // Property accessors

    public Integer getPrBasisId() {
        return this.prBasisId;
    }
    
    public void setPrBasisId(Integer prBasisId) {
        this.prBasisId = prBasisId;
    }

    public String getPrBasisDspName() {
        return this.prBasisDspName;
    }
    
    public void setPrBasisDspName(String prBasisDspName) {
        this.prBasisDspName = prBasisDspName;
    }

    public String getPrBasisDesc() {
        return this.prBasisDesc;
    }
    
    public void setPrBasisDesc(String prBasisDesc) {
        this.prBasisDesc = prBasisDesc;
    }

    public Set getRaTraceabilities() {
        return this.raTraceabilities;
    }
    
    public void setRaTraceabilities(Set raTraceabilities) {
        this.raTraceabilities = raTraceabilities;
    }
   








}