package com.kjnext.hibernate;



/**
 * RaProducerEventDataId generated by MyEclipse - Hibernate Tools
 */

public class RaProducerEventDataId  implements java.io.Serializable {


    // Fields    

     private Integer producerId;
     private Integer transId;


    // Constructors

    /** default constructor */
    public RaProducerEventDataId() {
    }

    
    /** full constructor */
    public RaProducerEventDataId(Integer producerId, Integer transId) {
        this.producerId = producerId;
        this.transId = transId;
    }

   
    // Property accessors

    public Integer getProducerId() {
        return this.producerId;
    }
    
    public void setProducerId(Integer producerId) {
        this.producerId = producerId;
    }

    public Integer getTransId() {
        return this.transId;
    }
    
    public void setTransId(Integer transId) {
        this.transId = transId;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RaProducerEventDataId) ) return false;
		 RaProducerEventDataId castOther = ( RaProducerEventDataId ) other; 
         
		 return ( (this.getProducerId()==castOther.getProducerId()) || ( this.getProducerId()!=null && castOther.getProducerId()!=null && this.getProducerId().equals(castOther.getProducerId()) ) )
 && ( (this.getTransId()==castOther.getTransId()) || ( this.getTransId()!=null && castOther.getTransId()!=null && this.getTransId().equals(castOther.getTransId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getProducerId() == null ? 0 : this.getProducerId().hashCode() );
         result = 37 * result + ( getTransId() == null ? 0 : this.getTransId().hashCode() );
         return result;
   }   





}