package com.kjnext.hibernate;

import java.util.Date;


/**
 * RaProducerEventData generated by MyEclipse - Hibernate Tools
 */

public class RaProducerEventData  implements java.io.Serializable {


    // Fields    

     private RaProducerEventDataId id;
     private String qtyViolation;
     private Date violationDate;
     private String farmName;


    // Constructors

    /** default constructor */
    public RaProducerEventData() {
    }

	/** minimal constructor */
    public RaProducerEventData(RaProducerEventDataId id) {
        this.id = id;
    }
    
    /** full constructor */
    public RaProducerEventData(RaProducerEventDataId id, String qtyViolation, Date violationDate, String farmName) {
        this.id = id;
        this.qtyViolation = qtyViolation;
        this.violationDate = violationDate;
        this.farmName = farmName;
    }

   
    // Property accessors

    public RaProducerEventDataId getId() {
        return this.id;
    }
    
    public void setId(RaProducerEventDataId id) {
        this.id = id;
    }

    public String getQtyViolation() {
        return this.qtyViolation;
    }
    
    public void setQtyViolation(String qtyViolation) {
        this.qtyViolation = qtyViolation;
    }

    public Date getViolationDate() {
        return this.violationDate;
    }
    
    public void setViolationDate(Date violationDate) {
        this.violationDate = violationDate;
    }

    public String getFarmName() {
        return this.farmName;
    }
    
    public void setFarmName(String farmName) {
        this.farmName = farmName;
    }
   








}