package com.kjnext.hibernate;



/**
 * RaProdReqInt generated by MyEclipse - Hibernate Tools
 */

public class RaProdReqInt  implements java.io.Serializable {


    // Fields    

     private Integer prodReqId;
     private String description;


    // Constructors

    /** default constructor */
    public RaProdReqInt() {
    }

	/** minimal constructor */
    public RaProdReqInt(Integer prodReqId) {
        this.prodReqId = prodReqId;
    }
    
    /** full constructor */
    public RaProdReqInt(Integer prodReqId, String description) {
        this.prodReqId = prodReqId;
        this.description = description;
    }

   
    // Property accessors

    public Integer getProdReqId() {
        return this.prodReqId;
    }
    
    public void setProdReqId(Integer prodReqId) {
        this.prodReqId = prodReqId;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
   








}