package com.kjnext.hibernate;

import java.util.Date;


/**
 * RaProducerDataUploadId generated by MyEclipse - Hibernate Tools
 */

public class RaProducerDataUploadId  implements java.io.Serializable {


    // Fields    

     private RaProducerMaster raProducerMaster;
     private String cerYear;
     private String farmName;
     private String variety;
     private String altitude;
     private Double totalHectares;
     private Double prodHectares;
     private String longitude;
     private String latitude;
     private String annualQty;
     private Date cerExpireDate;
     private String cerNumber;
     private String picturesUpload;
     private String farmUniqueInfo;
     private String specialProject;
     private String specialConservation;
     private String raBenefits;
     private String otherCerNumber;
     private Integer originId;
     private Integer gradeId;
     private Integer farmId;


    // Constructors

    /** default constructor */
    public RaProducerDataUploadId() {
    }

	/** minimal constructor */
    public RaProducerDataUploadId(RaProducerMaster raProducerMaster, String cerYear, String farmName) {
        this.raProducerMaster = raProducerMaster;
        this.cerYear = cerYear;
        this.farmName = farmName;
    }
    
    /** full constructor */
    public RaProducerDataUploadId(RaProducerMaster raProducerMaster, String cerYear, String farmName, String variety, String altitude, Double totalHectares, Double prodHectares, String longitude, String latitude, String annualQty, Date cerExpireDate, String cerNumber, String picturesUpload, String farmUniqueInfo, String specialProject, String specialConservation, String raBenefits, String otherCerNumber, Integer originId, Integer gradeId, Integer farmId) {
        this.raProducerMaster = raProducerMaster;
        this.cerYear = cerYear;
        this.farmName = farmName;
        this.variety = variety;
        this.altitude = altitude;
        this.totalHectares = totalHectares;
        this.prodHectares = prodHectares;
        this.longitude = longitude;
        this.latitude = latitude;
        this.annualQty = annualQty;
        this.cerExpireDate = cerExpireDate;
        this.cerNumber = cerNumber;
        this.picturesUpload = picturesUpload;
        this.farmUniqueInfo = farmUniqueInfo;
        this.specialProject = specialProject;
        this.specialConservation = specialConservation;
        this.raBenefits = raBenefits;
        this.otherCerNumber = otherCerNumber;
        this.originId = originId;
        this.gradeId = gradeId;
        this.farmId = farmId;
    }

   
    // Property accessors

    public RaProducerMaster getRaProducerMaster() {
        return this.raProducerMaster;
    }
    
    public void setRaProducerMaster(RaProducerMaster raProducerMaster) {
        this.raProducerMaster = raProducerMaster;
    }

    public String getCerYear() {
        return this.cerYear;
    }
    
    public void setCerYear(String cerYear) {
        this.cerYear = cerYear;
    }

    public String getFarmName() {
        return this.farmName;
    }
    
    public void setFarmName(String farmName) {
        this.farmName = farmName;
    }

    public String getVariety() {
        return this.variety;
    }
    
    public void setVariety(String variety) {
        this.variety = variety;
    }

    public String getAltitude() {
        return this.altitude;
    }
    
    public void setAltitude(String altitude) {
        this.altitude = altitude;
    }

    public Double getTotalHectares() {
        return this.totalHectares;
    }
    
    public void setTotalHectares(Double totalHectares) {
        this.totalHectares = totalHectares;
    }

    public Double getProdHectares() {
        return this.prodHectares;
    }
    
    public void setProdHectares(Double prodHectares) {
        this.prodHectares = prodHectares;
    }

    public String getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    public String getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    public String getAnnualQty() {
        return this.annualQty;
    }
    
    public void setAnnualQty(String annualQty) {
        this.annualQty = annualQty;
    }

    public Date getCerExpireDate() {
        return this.cerExpireDate;
    }
    
    public void setCerExpireDate(Date cerExpireDate) {
        this.cerExpireDate = cerExpireDate;
    }

    public String getCerNumber() {
        return this.cerNumber;
    }
    
    public void setCerNumber(String cerNumber) {
        this.cerNumber = cerNumber;
    }

    public String getPicturesUpload() {
        return this.picturesUpload;
    }
    
    public void setPicturesUpload(String picturesUpload) {
        this.picturesUpload = picturesUpload;
    }

    public String getFarmUniqueInfo() {
        return this.farmUniqueInfo;
    }
    
    public void setFarmUniqueInfo(String farmUniqueInfo) {
        this.farmUniqueInfo = farmUniqueInfo;
    }

    public String getSpecialProject() {
        return this.specialProject;
    }
    
    public void setSpecialProject(String specialProject) {
        this.specialProject = specialProject;
    }

    public String getSpecialConservation() {
        return this.specialConservation;
    }
    
    public void setSpecialConservation(String specialConservation) {
        this.specialConservation = specialConservation;
    }

    public String getRaBenefits() {
        return this.raBenefits;
    }
    
    public void setRaBenefits(String raBenefits) {
        this.raBenefits = raBenefits;
    }

    public String getOtherCerNumber() {
        return this.otherCerNumber;
    }
    
    public void setOtherCerNumber(String otherCerNumber) {
        this.otherCerNumber = otherCerNumber;
    }

    public Integer getOriginId() {
        return this.originId;
    }
    
    public void setOriginId(Integer originId) {
        this.originId = originId;
    }

    public Integer getGradeId() {
        return this.gradeId;
    }
    
    public void setGradeId(Integer gradeId) {
        this.gradeId = gradeId;
    }

    public Integer getFarmId() {
        return this.farmId;
    }
    
    public void setFarmId(Integer farmId) {
        this.farmId = farmId;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RaProducerDataUploadId) ) return false;
		 RaProducerDataUploadId castOther = ( RaProducerDataUploadId ) other; 
         
		 return ( (this.getRaProducerMaster()==castOther.getRaProducerMaster()) || ( this.getRaProducerMaster()!=null && castOther.getRaProducerMaster()!=null && this.getRaProducerMaster().equals(castOther.getRaProducerMaster()) ) )
 && ( (this.getCerYear()==castOther.getCerYear()) || ( this.getCerYear()!=null && castOther.getCerYear()!=null && this.getCerYear().equals(castOther.getCerYear()) ) )
 && ( (this.getFarmName()==castOther.getFarmName()) || ( this.getFarmName()!=null && castOther.getFarmName()!=null && this.getFarmName().equals(castOther.getFarmName()) ) )
 && ( (this.getVariety()==castOther.getVariety()) || ( this.getVariety()!=null && castOther.getVariety()!=null && this.getVariety().equals(castOther.getVariety()) ) )
 && ( (this.getAltitude()==castOther.getAltitude()) || ( this.getAltitude()!=null && castOther.getAltitude()!=null && this.getAltitude().equals(castOther.getAltitude()) ) )
 && ( (this.getTotalHectares()==castOther.getTotalHectares()) || ( this.getTotalHectares()!=null && castOther.getTotalHectares()!=null && this.getTotalHectares().equals(castOther.getTotalHectares()) ) )
 && ( (this.getProdHectares()==castOther.getProdHectares()) || ( this.getProdHectares()!=null && castOther.getProdHectares()!=null && this.getProdHectares().equals(castOther.getProdHectares()) ) )
 && ( (this.getLongitude()==castOther.getLongitude()) || ( this.getLongitude()!=null && castOther.getLongitude()!=null && this.getLongitude().equals(castOther.getLongitude()) ) )
 && ( (this.getLatitude()==castOther.getLatitude()) || ( this.getLatitude()!=null && castOther.getLatitude()!=null && this.getLatitude().equals(castOther.getLatitude()) ) )
 && ( (this.getAnnualQty()==castOther.getAnnualQty()) || ( this.getAnnualQty()!=null && castOther.getAnnualQty()!=null && this.getAnnualQty().equals(castOther.getAnnualQty()) ) )
 && ( (this.getCerExpireDate()==castOther.getCerExpireDate()) || ( this.getCerExpireDate()!=null && castOther.getCerExpireDate()!=null && this.getCerExpireDate().equals(castOther.getCerExpireDate()) ) )
 && ( (this.getCerNumber()==castOther.getCerNumber()) || ( this.getCerNumber()!=null && castOther.getCerNumber()!=null && this.getCerNumber().equals(castOther.getCerNumber()) ) )
 && ( (this.getPicturesUpload()==castOther.getPicturesUpload()) || ( this.getPicturesUpload()!=null && castOther.getPicturesUpload()!=null && this.getPicturesUpload().equals(castOther.getPicturesUpload()) ) )
 && ( (this.getFarmUniqueInfo()==castOther.getFarmUniqueInfo()) || ( this.getFarmUniqueInfo()!=null && castOther.getFarmUniqueInfo()!=null && this.getFarmUniqueInfo().equals(castOther.getFarmUniqueInfo()) ) )
 && ( (this.getSpecialProject()==castOther.getSpecialProject()) || ( this.getSpecialProject()!=null && castOther.getSpecialProject()!=null && this.getSpecialProject().equals(castOther.getSpecialProject()) ) )
 && ( (this.getSpecialConservation()==castOther.getSpecialConservation()) || ( this.getSpecialConservation()!=null && castOther.getSpecialConservation()!=null && this.getSpecialConservation().equals(castOther.getSpecialConservation()) ) )
 && ( (this.getRaBenefits()==castOther.getRaBenefits()) || ( this.getRaBenefits()!=null && castOther.getRaBenefits()!=null && this.getRaBenefits().equals(castOther.getRaBenefits()) ) )
 && ( (this.getOtherCerNumber()==castOther.getOtherCerNumber()) || ( this.getOtherCerNumber()!=null && castOther.getOtherCerNumber()!=null && this.getOtherCerNumber().equals(castOther.getOtherCerNumber()) ) )
 && ( (this.getOriginId()==castOther.getOriginId()) || ( this.getOriginId()!=null && castOther.getOriginId()!=null && this.getOriginId().equals(castOther.getOriginId()) ) )
 && ( (this.getGradeId()==castOther.getGradeId()) || ( this.getGradeId()!=null && castOther.getGradeId()!=null && this.getGradeId().equals(castOther.getGradeId()) ) )
 && ( (this.getFarmId()==castOther.getFarmId()) || ( this.getFarmId()!=null && castOther.getFarmId()!=null && this.getFarmId().equals(castOther.getFarmId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRaProducerMaster() == null ? 0 : this.getRaProducerMaster().hashCode() );
         result = 37 * result + ( getCerYear() == null ? 0 : this.getCerYear().hashCode() );
         result = 37 * result + ( getFarmName() == null ? 0 : this.getFarmName().hashCode() );
         result = 37 * result + ( getVariety() == null ? 0 : this.getVariety().hashCode() );
         result = 37 * result + ( getAltitude() == null ? 0 : this.getAltitude().hashCode() );
         result = 37 * result + ( getTotalHectares() == null ? 0 : this.getTotalHectares().hashCode() );
         result = 37 * result + ( getProdHectares() == null ? 0 : this.getProdHectares().hashCode() );
         result = 37 * result + ( getLongitude() == null ? 0 : this.getLongitude().hashCode() );
         result = 37 * result + ( getLatitude() == null ? 0 : this.getLatitude().hashCode() );
         result = 37 * result + ( getAnnualQty() == null ? 0 : this.getAnnualQty().hashCode() );
         result = 37 * result + ( getCerExpireDate() == null ? 0 : this.getCerExpireDate().hashCode() );
         result = 37 * result + ( getCerNumber() == null ? 0 : this.getCerNumber().hashCode() );
         result = 37 * result + ( getPicturesUpload() == null ? 0 : this.getPicturesUpload().hashCode() );
         result = 37 * result + ( getFarmUniqueInfo() == null ? 0 : this.getFarmUniqueInfo().hashCode() );
         result = 37 * result + ( getSpecialProject() == null ? 0 : this.getSpecialProject().hashCode() );
         result = 37 * result + ( getSpecialConservation() == null ? 0 : this.getSpecialConservation().hashCode() );
         result = 37 * result + ( getRaBenefits() == null ? 0 : this.getRaBenefits().hashCode() );
         result = 37 * result + ( getOtherCerNumber() == null ? 0 : this.getOtherCerNumber().hashCode() );
         result = 37 * result + ( getOriginId() == null ? 0 : this.getOriginId().hashCode() );
         result = 37 * result + ( getGradeId() == null ? 0 : this.getGradeId().hashCode() );
         result = 37 * result + ( getFarmId() == null ? 0 : this.getFarmId().hashCode() );
         return result;
   }   





}