package com.kjnext.hibernate;



/**
 * RaProdRegion generated by MyEclipse - Hibernate Tools
 */

public class RaProdRegion  implements java.io.Serializable {


    // Fields    

     private Integer prodRegionId;
     private RaOriginMaster raOriginMaster;
     private String prodDescription;
     private String prodRegionType;
     private String prodStatus;


    // Constructors

    /** default constructor */
    public RaProdRegion() {
    }

	/** minimal constructor */
    public RaProdRegion(Integer prodRegionId) {
        this.prodRegionId = prodRegionId;
    }
    
    /** full constructor */
    public RaProdRegion(Integer prodRegionId, RaOriginMaster raOriginMaster, String prodDescription, String prodRegionType, String prodStatus) {
        this.prodRegionId = prodRegionId;
        this.raOriginMaster = raOriginMaster;
        this.prodDescription = prodDescription;
        this.prodRegionType = prodRegionType;
        this.prodStatus = prodStatus;
    }

   
    // Property accessors

    public Integer getProdRegionId() {
        return this.prodRegionId;
    }
    
    public void setProdRegionId(Integer prodRegionId) {
        this.prodRegionId = prodRegionId;
    }

    public RaOriginMaster getRaOriginMaster() {
        return this.raOriginMaster;
    }
    
    public void setRaOriginMaster(RaOriginMaster raOriginMaster) {
        this.raOriginMaster = raOriginMaster;
    }

    public String getProdDescription() {
        return this.prodDescription;
    }
    
    public void setProdDescription(String prodDescription) {
        this.prodDescription = prodDescription;
    }

    public String getProdRegionType() {
        return this.prodRegionType;
    }
    
    public void setProdRegionType(String prodRegionType) {
        this.prodRegionType = prodRegionType;
    }

    public String getProdStatus() {
        return this.prodStatus;
    }
    
    public void setProdStatus(String prodStatus) {
        this.prodStatus = prodStatus;
    }
   








}