package com.kjnext.hibernate;



/**
 * RaProducerEventDataEdit generated by MyEclipse - Hibernate Tools
 */

public class RaProducerEventDataEdit  implements java.io.Serializable {


    // Fields    

     private RaProducerEventDataEditId id;


    // Constructors

    /** default constructor */
    public RaProducerEventDataEdit() {
    }

    
    /** full constructor */
    public RaProducerEventDataEdit(RaProducerEventDataEditId id) {
        this.id = id;
    }

   
    // Property accessors

    public RaProducerEventDataEditId getId() {
        return this.id;
    }
    
    public void setId(RaProducerEventDataEditId id) {
        this.id = id;
    }
   








}