package com.kjnext.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * RaProductMaster generated by MyEclipse - Hibernate Tools
 */

public class RaProductMaster  implements java.io.Serializable {


    // Fields    

     private Integer productId;
     private String description;
     private String productStatus;
     private String productType;
     private Set raCompanyProducts = new HashSet(0);
     private Set raRequestProducts = new HashSet(0);
     private Set raSealProducts = new HashSet(0);
     private Integer[] companyProduct;

    // Constructors

    public Integer[] getCompanyProduct() {
		return companyProduct;
	}

	public void setCompanyProduct(Integer[] companyProduct) {
		this.companyProduct = companyProduct;
	}

	/** default constructor */
    public RaProductMaster() {
    }

	/** minimal constructor */
    public RaProductMaster(Integer productId) {
        this.productId = productId;
    }
    
    /** full constructor */
    public RaProductMaster(Integer productId, String description, String productStatus, String productType, Set raCompanyProducts, Set raRequestProducts, Set raSealProducts) {
        this.productId = productId;
        this.description = description;
        this.productStatus = productStatus;
        this.productType = productType;
        this.raCompanyProducts = raCompanyProducts;
        this.raRequestProducts = raRequestProducts;
        this.raSealProducts = raSealProducts;
    }

   
    // Property accessors

    public Integer getProductId() {
        return this.productId;
    }
    
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public String getProductStatus() {
        return this.productStatus;
    }
    
    public void setProductStatus(String productStatus) {
        this.productStatus = productStatus;
    }

    public String getProductType() {
        return this.productType;
    }
    
    public void setProductType(String productType) {
        this.productType = productType;
    }

    public Set getRaCompanyProducts() {
        return this.raCompanyProducts;
    }
    
    public void setRaCompanyProducts(Set raCompanyProducts) {
        this.raCompanyProducts = raCompanyProducts;
    }

    public Set getRaRequestProducts() {
        return this.raRequestProducts;
    }
    
    public void setRaRequestProducts(Set raRequestProducts) {
        this.raRequestProducts = raRequestProducts;
    }

    public Set getRaSealProducts() {
        return this.raSealProducts;
    }
    
    public void setRaSealProducts(Set raSealProducts) {
        this.raSealProducts = raSealProducts;
    }
   








}