package com.kjnext.hibernate;

import java.util.Date;


/**
 * RaProducerEventDataEditId generated by MyEclipse - Hibernate Tools
 */

public class RaProducerEventDataEditId  implements java.io.Serializable {


    // Fields    

     private Integer producerId;
     private String qtyViolation;
     private Integer transId;
     private Date violationDate;
     private String farmName;


    // Constructors

    /** default constructor */
    public RaProducerEventDataEditId() {
    }

	/** minimal constructor */
    public RaProducerEventDataEditId(Integer transId) {
        this.transId = transId;
    }
    
    /** full constructor */
    public RaProducerEventDataEditId(Integer producerId, String qtyViolation, Integer transId, Date violationDate, String farmName) {
        this.producerId = producerId;
        this.qtyViolation = qtyViolation;
        this.transId = transId;
        this.violationDate = violationDate;
        this.farmName = farmName;
    }

   
    // Property accessors

    public Integer getProducerId() {
        return this.producerId;
    }
    
    public void setProducerId(Integer producerId) {
        this.producerId = producerId;
    }

    public String getQtyViolation() {
        return this.qtyViolation;
    }
    
    public void setQtyViolation(String qtyViolation) {
        this.qtyViolation = qtyViolation;
    }

    public Integer getTransId() {
        return this.transId;
    }
    
    public void setTransId(Integer transId) {
        this.transId = transId;
    }

    public Date getViolationDate() {
        return this.violationDate;
    }
    
    public void setViolationDate(Date violationDate) {
        this.violationDate = violationDate;
    }

    public String getFarmName() {
        return this.farmName;
    }
    
    public void setFarmName(String farmName) {
        this.farmName = farmName;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RaProducerEventDataEditId) ) return false;
		 RaProducerEventDataEditId castOther = ( RaProducerEventDataEditId ) other; 
         
		 return ( (this.getProducerId()==castOther.getProducerId()) || ( this.getProducerId()!=null && castOther.getProducerId()!=null && this.getProducerId().equals(castOther.getProducerId()) ) )
 && ( (this.getQtyViolation()==castOther.getQtyViolation()) || ( this.getQtyViolation()!=null && castOther.getQtyViolation()!=null && this.getQtyViolation().equals(castOther.getQtyViolation()) ) )
 && ( (this.getTransId()==castOther.getTransId()) || ( this.getTransId()!=null && castOther.getTransId()!=null && this.getTransId().equals(castOther.getTransId()) ) )
 && ( (this.getViolationDate()==castOther.getViolationDate()) || ( this.getViolationDate()!=null && castOther.getViolationDate()!=null && this.getViolationDate().equals(castOther.getViolationDate()) ) )
 && ( (this.getFarmName()==castOther.getFarmName()) || ( this.getFarmName()!=null && castOther.getFarmName()!=null && this.getFarmName().equals(castOther.getFarmName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getProducerId() == null ? 0 : this.getProducerId().hashCode() );
         result = 37 * result + ( getQtyViolation() == null ? 0 : this.getQtyViolation().hashCode() );
         result = 37 * result + ( getTransId() == null ? 0 : this.getTransId().hashCode() );
         result = 37 * result + ( getViolationDate() == null ? 0 : this.getViolationDate().hashCode() );
         result = 37 * result + ( getFarmName() == null ? 0 : this.getFarmName().hashCode() );
         return result;
   }   





}