package com.kjnext.hibernate;



/**
 * RaRequestBuss generated by MyEclipse - Hibernate Tools
 */

public class RaRequestBuss  implements java.io.Serializable {


    // Fields    

     private RaRequestBussId id;


    // Constructors

    /** default constructor */
    public RaRequestBuss() {
    }

    
    /** full constructor */
    public RaRequestBuss(RaRequestBussId id) {
        this.id = id;
    }

   
    // Property accessors

    public RaRequestBussId getId() {
        return this.id;
    }
    
    public void setId(RaRequestBussId id) {
        this.id = id;
    }
   








}