package com.kjnext.hibernate;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * RaRequestInfo generated by MyEclipse - Hibernate Tools
 */

public class RaRequestInfo  implements java.io.Serializable {


    // Fields    

     private Integer requestId;
     private Date createDate;
     private Date modifyDate;
     private String companyName;
     private String firstName;
     private String companyHolding;
     private String position;
     private String offAddress;
     private String city;
     private String state;
     private String zip;
     private Integer countryId;
     private String phone;
     private String fax;
     private String email;
     private String comments;
     private String requestStatus;
     private String otherBussType;
     private String otherProduct;
     private Integer prodReqId;
     private String prodReqOther;
     private String prodInterest;
     private Set raRequestProducts = new HashSet(0);
     private Set raRequestBusses = new HashSet(0);


    // Constructors

    /** default constructor */
    public RaRequestInfo() {
    }

	/** minimal constructor */
    public RaRequestInfo(Integer requestId) {
        this.requestId = requestId;
    }
    
    /** full constructor */
    public RaRequestInfo(Integer requestId, Date createDate, Date modifyDate, String companyName, String firstName, String companyHolding, String position, String offAddress, String city, String state, String zip, Integer countryId, String phone, String fax, String email, String comments, String requestStatus, String otherBussType, String otherProduct, Integer prodReqId, String prodReqOther, String prodInterest, Set raRequestProducts, Set raRequestBusses) {
        this.requestId = requestId;
        this.createDate = createDate;
        this.modifyDate = modifyDate;
        this.companyName = companyName;
        this.firstName = firstName;
        this.companyHolding = companyHolding;
        this.position = position;
        this.offAddress = offAddress;
        this.city = city;
        this.state = state;
        this.zip = zip;
        this.countryId = countryId;
        this.phone = phone;
        this.fax = fax;
        this.email = email;
        this.comments = comments;
        this.requestStatus = requestStatus;
        this.otherBussType = otherBussType;
        this.otherProduct = otherProduct;
        this.prodReqId = prodReqId;
        this.prodReqOther = prodReqOther;
        this.prodInterest = prodInterest;
        this.raRequestProducts = raRequestProducts;
        this.raRequestBusses = raRequestBusses;
    }

   
    // Property accessors

    public Integer getRequestId() {
        return this.requestId;
    }
    
    public void setRequestId(Integer requestId) {
        this.requestId = requestId;
    }

    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public Date getModifyDate() {
        return this.modifyDate;
    }
    
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getCompanyHolding() {
        return this.companyHolding;
    }
    
    public void setCompanyHolding(String companyHolding) {
        this.companyHolding = companyHolding;
    }

    public String getPosition() {
        return this.position;
    }
    
    public void setPosition(String position) {
        this.position = position;
    }

    public String getOffAddress() {
        return this.offAddress;
    }
    
    public void setOffAddress(String offAddress) {
        this.offAddress = offAddress;
    }

    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }

    public String getZip() {
        return this.zip;
    }
    
    public void setZip(String zip) {
        this.zip = zip;
    }

    public Integer getCountryId() {
        return this.countryId;
    }
    
    public void setCountryId(Integer countryId) {
        this.countryId = countryId;
    }

    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }

    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }

    public String getRequestStatus() {
        return this.requestStatus;
    }
    
    public void setRequestStatus(String requestStatus) {
        this.requestStatus = requestStatus;
    }

    public String getOtherBussType() {
        return this.otherBussType;
    }
    
    public void setOtherBussType(String otherBussType) {
        this.otherBussType = otherBussType;
    }

    public String getOtherProduct() {
        return this.otherProduct;
    }
    
    public void setOtherProduct(String otherProduct) {
        this.otherProduct = otherProduct;
    }

    public Integer getProdReqId() {
        return this.prodReqId;
    }
    
    public void setProdReqId(Integer prodReqId) {
        this.prodReqId = prodReqId;
    }

    public String getProdReqOther() {
        return this.prodReqOther;
    }
    
    public void setProdReqOther(String prodReqOther) {
        this.prodReqOther = prodReqOther;
    }

    public String getProdInterest() {
        return this.prodInterest;
    }
    
    public void setProdInterest(String prodInterest) {
        this.prodInterest = prodInterest;
    }

    public Set getRaRequestProducts() {
        return this.raRequestProducts;
    }
    
    public void setRaRequestProducts(Set raRequestProducts) {
        this.raRequestProducts = raRequestProducts;
    }

    public Set getRaRequestBusses() {
        return this.raRequestBusses;
    }
    
    public void setRaRequestBusses(Set raRequestBusses) {
        this.raRequestBusses = raRequestBusses;
    }
   








}