package com.kjnext.hibernate;



/**
 * RaRequestProduct generated by MyEclipse - Hibernate Tools
 */

public class RaRequestProduct  implements java.io.Serializable {


    // Fields    

     private RaRequestProductId id;


    // Constructors

    /** default constructor */
    public RaRequestProduct() {
    }

    
    /** full constructor */
    public RaRequestProduct(RaRequestProductId id) {
        this.id = id;
    }

   
    // Property accessors

    public RaRequestProductId getId() {
        return this.id;
    }
    
    public void setId(RaRequestProductId id) {
        this.id = id;
    }
   








}