package com.kjnext.hibernate;



/**
 * RaRequestProductId generated by MyEclipse - Hibernate Tools
 */

public class RaRequestProductId  implements java.io.Serializable {


    // Fields    

     private RaRequestInfo raRequestInfo;
     private RaProductMaster raProductMaster;


    // Constructors

    /** default constructor */
    public RaRequestProductId() {
    }

    
    /** full constructor */
    public RaRequestProductId(RaRequestInfo raRequestInfo, RaProductMaster raProductMaster) {
        this.raRequestInfo = raRequestInfo;
        this.raProductMaster = raProductMaster;
    }

   
    // Property accessors

    public RaRequestInfo getRaRequestInfo() {
        return this.raRequestInfo;
    }
    
    public void setRaRequestInfo(RaRequestInfo raRequestInfo) {
        this.raRequestInfo = raRequestInfo;
    }

    public RaProductMaster getRaProductMaster() {
        return this.raProductMaster;
    }
    
    public void setRaProductMaster(RaProductMaster raProductMaster) {
        this.raProductMaster = raProductMaster;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RaRequestProductId) ) return false;
		 RaRequestProductId castOther = ( RaRequestProductId ) other; 
         
		 return ( (this.getRaRequestInfo()==castOther.getRaRequestInfo()) || ( this.getRaRequestInfo()!=null && castOther.getRaRequestInfo()!=null && this.getRaRequestInfo().equals(castOther.getRaRequestInfo()) ) )
 && ( (this.getRaProductMaster()==castOther.getRaProductMaster()) || ( this.getRaProductMaster()!=null && castOther.getRaProductMaster()!=null && this.getRaProductMaster().equals(castOther.getRaProductMaster()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRaRequestInfo() == null ? 0 : this.getRaRequestInfo().hashCode() );
         result = 37 * result + ( getRaProductMaster() == null ? 0 : this.getRaProductMaster().hashCode() );
         return result;
   }   





}