package com.kjnext.hibernate;



/**
 * RaRequestBussId generated by MyEclipse - Hibernate Tools
 */

public class RaRequestBussId  implements java.io.Serializable {


    // Fields    

     private RaRequestInfo raRequestInfo;
     private RaBussinessTypeMaster raBussinessTypeMaster;


    // Constructors

    /** default constructor */
    public RaRequestBussId() {
    }

    
    /** full constructor */
    public RaRequestBussId(RaRequestInfo raRequestInfo, RaBussinessTypeMaster raBussinessTypeMaster) {
        this.raRequestInfo = raRequestInfo;
        this.raBussinessTypeMaster = raBussinessTypeMaster;
    }

   
    // Property accessors

    public RaRequestInfo getRaRequestInfo() {
        return this.raRequestInfo;
    }
    
    public void setRaRequestInfo(RaRequestInfo raRequestInfo) {
        this.raRequestInfo = raRequestInfo;
    }

    public RaBussinessTypeMaster getRaBussinessTypeMaster() {
        return this.raBussinessTypeMaster;
    }
    
    public void setRaBussinessTypeMaster(RaBussinessTypeMaster raBussinessTypeMaster) {
        this.raBussinessTypeMaster = raBussinessTypeMaster;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RaRequestBussId) ) return false;
		 RaRequestBussId castOther = ( RaRequestBussId ) other; 
         
		 return ( (this.getRaRequestInfo()==castOther.getRaRequestInfo()) || ( this.getRaRequestInfo()!=null && castOther.getRaRequestInfo()!=null && this.getRaRequestInfo().equals(castOther.getRaRequestInfo()) ) )
 && ( (this.getRaBussinessTypeMaster()==castOther.getRaBussinessTypeMaster()) || ( this.getRaBussinessTypeMaster()!=null && castOther.getRaBussinessTypeMaster()!=null && this.getRaBussinessTypeMaster().equals(castOther.getRaBussinessTypeMaster()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRaRequestInfo() == null ? 0 : this.getRaRequestInfo().hashCode() );
         result = 37 * result + ( getRaBussinessTypeMaster() == null ? 0 : this.getRaBussinessTypeMaster().hashCode() );
         return result;
   }   





}