package com.kjnext.hibernate;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * RaSealMaster generated by MyEclipse - Hibernate Tools
 */

public class RaSealMaster  implements java.io.Serializable {


    // Fields    

     private Integer sealId;
     private Integer companyId;
     private String name;
     private String email;
     private String uploadData1;
     private String uploadData2;
     private String uploadData3;
     private String uploadData4;
     private Date applicationDate;
     private Date launchDate;
     private String regAreas;
     private String blendRaCerContent;
     private String prodContent;
     private String sellProdOutlet;
     private String otherSealProd;
     private String otherMaterial;
     private String otherOutlet;
     private String sealStatus;
     private String otherRegion;
     private String otherSupplier;
     private String applicationComments;
     private String optional;
     private String mandatory;
     private Set raSealStates = new HashSet(0);
     private Set raSealProducts = new HashSet(0);
     private Set raSealMaterials = new HashSet(0);
     private Set raSealSuppliers = new HashSet(0);
     private Set raSealHistories = new HashSet(0);
     private Set raSealBrands = new HashSet(0);


    // Constructors

    /** default constructor */
    public RaSealMaster() {
    }

	/** minimal constructor */
    public RaSealMaster(Integer sealId) {
        this.sealId = sealId;
    }
    
    /** full constructor */
    public RaSealMaster(Integer sealId, Integer companyId, String name, String email, String uploadData1, String uploadData2, String uploadData3, String uploadData4, Date applicationDate, Date launchDate, String regAreas, String blendRaCerContent, String prodContent, String sellProdOutlet, String otherSealProd, String otherMaterial, String otherOutlet, String sealStatus, String otherRegion, String otherSupplier, String applicationComments, String optional, String mandatory, Set raSealStates, Set raSealProducts, Set raSealMaterials, Set raSealSuppliers, Set raSealHistories, Set raSealBrands) {
        this.sealId = sealId;
        this.companyId = companyId;
        this.name = name;
        this.email = email;
        this.uploadData1 = uploadData1;
        this.uploadData2 = uploadData2;
        this.uploadData3 = uploadData3;
        this.uploadData4 = uploadData4;
        this.applicationDate = applicationDate;
        this.launchDate = launchDate;
        this.regAreas = regAreas;
        this.blendRaCerContent = blendRaCerContent;
        this.prodContent = prodContent;
        this.sellProdOutlet = sellProdOutlet;
        this.otherSealProd = otherSealProd;
        this.otherMaterial = otherMaterial;
        this.otherOutlet = otherOutlet;
        this.sealStatus = sealStatus;
        this.otherRegion = otherRegion;
        this.otherSupplier = otherSupplier;
        this.applicationComments = applicationComments;
        this.optional = optional;
        this.mandatory = mandatory;
        this.raSealStates = raSealStates;
        this.raSealProducts = raSealProducts;
        this.raSealMaterials = raSealMaterials;
        this.raSealSuppliers = raSealSuppliers;
        this.raSealHistories = raSealHistories;
        this.raSealBrands = raSealBrands;
    }

   
    // Property accessors

    public Integer getSealId() {
        return this.sealId;
    }
    
    public void setSealId(Integer sealId) {
        this.sealId = sealId;
    }

    public Integer getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    public String getUploadData1() {
        return this.uploadData1;
    }
    
    public void setUploadData1(String uploadData1) {
        this.uploadData1 = uploadData1;
    }

    public String getUploadData2() {
        return this.uploadData2;
    }
    
    public void setUploadData2(String uploadData2) {
        this.uploadData2 = uploadData2;
    }

    public String getUploadData3() {
        return this.uploadData3;
    }
    
    public void setUploadData3(String uploadData3) {
        this.uploadData3 = uploadData3;
    }

    public String getUploadData4() {
        return this.uploadData4;
    }
    
    public void setUploadData4(String uploadData4) {
        this.uploadData4 = uploadData4;
    }

    public Date getApplicationDate() {
        return this.applicationDate;
    }
    
    public void setApplicationDate(Date applicationDate) {
        this.applicationDate = applicationDate;
    }

    public Date getLaunchDate() {
        return this.launchDate;
    }
    
    public void setLaunchDate(Date launchDate) {
        this.launchDate = launchDate;
    }

    public String getRegAreas() {
        return this.regAreas;
    }
    
    public void setRegAreas(String regAreas) {
        this.regAreas = regAreas;
    }

    public String getBlendRaCerContent() {
        return this.blendRaCerContent;
    }
    
    public void setBlendRaCerContent(String blendRaCerContent) {
        this.blendRaCerContent = blendRaCerContent;
    }

    public String getProdContent() {
        return this.prodContent;
    }
    
    public void setProdContent(String prodContent) {
        this.prodContent = prodContent;
    }

    public String getSellProdOutlet() {
        return this.sellProdOutlet;
    }
    
    public void setSellProdOutlet(String sellProdOutlet) {
        this.sellProdOutlet = sellProdOutlet;
    }

    public String getOtherSealProd() {
        return this.otherSealProd;
    }
    
    public void setOtherSealProd(String otherSealProd) {
        this.otherSealProd = otherSealProd;
    }

    public String getOtherMaterial() {
        return this.otherMaterial;
    }
    
    public void setOtherMaterial(String otherMaterial) {
        this.otherMaterial = otherMaterial;
    }

    public String getOtherOutlet() {
        return this.otherOutlet;
    }
    
    public void setOtherOutlet(String otherOutlet) {
        this.otherOutlet = otherOutlet;
    }

    public String getSealStatus() {
        return this.sealStatus;
    }
    
    public void setSealStatus(String sealStatus) {
        this.sealStatus = sealStatus;
    }

    public String getOtherRegion() {
        return this.otherRegion;
    }
    
    public void setOtherRegion(String otherRegion) {
        this.otherRegion = otherRegion;
    }

    public String getOtherSupplier() {
        return this.otherSupplier;
    }
    
    public void setOtherSupplier(String otherSupplier) {
        this.otherSupplier = otherSupplier;
    }

    public String getApplicationComments() {
        return this.applicationComments;
    }
    
    public void setApplicationComments(String applicationComments) {
        this.applicationComments = applicationComments;
    }

    public String getOptional() {
        return this.optional;
    }
    
    public void setOptional(String optional) {
        this.optional = optional;
    }

    public String getMandatory() {
        return this.mandatory;
    }
    
    public void setMandatory(String mandatory) {
        this.mandatory = mandatory;
    }

    public Set getRaSealStates() {
        return this.raSealStates;
    }
    
    public void setRaSealStates(Set raSealStates) {
        this.raSealStates = raSealStates;
    }

    public Set getRaSealProducts() {
        return this.raSealProducts;
    }
    
    public void setRaSealProducts(Set raSealProducts) {
        this.raSealProducts = raSealProducts;
    }

    public Set getRaSealMaterials() {
        return this.raSealMaterials;
    }
    
    public void setRaSealMaterials(Set raSealMaterials) {
        this.raSealMaterials = raSealMaterials;
    }

    public Set getRaSealSuppliers() {
        return this.raSealSuppliers;
    }
    
    public void setRaSealSuppliers(Set raSealSuppliers) {
        this.raSealSuppliers = raSealSuppliers;
    }

    public Set getRaSealHistories() {
        return this.raSealHistories;
    }
    
    public void setRaSealHistories(Set raSealHistories) {
        this.raSealHistories = raSealHistories;
    }

    public Set getRaSealBrands() {
        return this.raSealBrands;
    }
    
    public void setRaSealBrands(Set raSealBrands) {
        this.raSealBrands = raSealBrands;
    }
   








}