package com.kjnext.hibernate;



/**
 * RaSealStateId generated by MyEclipse - Hibernate Tools
 */

public class RaSealStateId  implements java.io.Serializable {


    // Fields    

     private RaSealMaster raSealMaster;
     private Integer regionId;
     private RaStateMaster raStateMaster;


    // Constructors

    /** default constructor */
    public RaSealStateId() {
    }

    
    /** full constructor */
    public RaSealStateId(RaSealMaster raSealMaster, Integer regionId, RaStateMaster raStateMaster) {
        this.raSealMaster = raSealMaster;
        this.regionId = regionId;
        this.raStateMaster = raStateMaster;
    }

   
    // Property accessors

    public RaSealMaster getRaSealMaster() {
        return this.raSealMaster;
    }
    
    public void setRaSealMaster(RaSealMaster raSealMaster) {
        this.raSealMaster = raSealMaster;
    }

    public Integer getRegionId() {
        return this.regionId;
    }
    
    public void setRegionId(Integer regionId) {
        this.regionId = regionId;
    }

    public RaStateMaster getRaStateMaster() {
        return this.raStateMaster;
    }
    
    public void setRaStateMaster(RaStateMaster raStateMaster) {
        this.raStateMaster = raStateMaster;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RaSealStateId) ) return false;
		 RaSealStateId castOther = ( RaSealStateId ) other; 
         
		 return ( (this.getRaSealMaster()==castOther.getRaSealMaster()) || ( this.getRaSealMaster()!=null && castOther.getRaSealMaster()!=null && this.getRaSealMaster().equals(castOther.getRaSealMaster()) ) )
 && ( (this.getRegionId()==castOther.getRegionId()) || ( this.getRegionId()!=null && castOther.getRegionId()!=null && this.getRegionId().equals(castOther.getRegionId()) ) )
 && ( (this.getRaStateMaster()==castOther.getRaStateMaster()) || ( this.getRaStateMaster()!=null && castOther.getRaStateMaster()!=null && this.getRaStateMaster().equals(castOther.getRaStateMaster()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRaSealMaster() == null ? 0 : this.getRaSealMaster().hashCode() );
         result = 37 * result + ( getRegionId() == null ? 0 : this.getRegionId().hashCode() );
         result = 37 * result + ( getRaStateMaster() == null ? 0 : this.getRaStateMaster().hashCode() );
         return result;
   }   





}