package com.kjnext.hibernate;



/**
 * RaSealSupplierId generated by MyEclipse - Hibernate Tools
 */

public class RaSealSupplierId  implements java.io.Serializable {


    // Fields    

     private Integer companyId;
     private RaSealMaster raSealMaster;
     private Integer supplierType;


    // Constructors

    /** default constructor */
    public RaSealSupplierId() {
    }

    
    /** full constructor */
    public RaSealSupplierId(Integer companyId, RaSealMaster raSealMaster, Integer supplierType) {
        this.companyId = companyId;
        this.raSealMaster = raSealMaster;
        this.supplierType = supplierType;
    }

   
    // Property accessors

    public Integer getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    public RaSealMaster getRaSealMaster() {
        return this.raSealMaster;
    }
    
    public void setRaSealMaster(RaSealMaster raSealMaster) {
        this.raSealMaster = raSealMaster;
    }

    public Integer getSupplierType() {
        return this.supplierType;
    }
    
    public void setSupplierType(Integer supplierType) {
        this.supplierType = supplierType;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RaSealSupplierId) ) return false;
		 RaSealSupplierId castOther = ( RaSealSupplierId ) other; 
         
		 return ( (this.getCompanyId()==castOther.getCompanyId()) || ( this.getCompanyId()!=null && castOther.getCompanyId()!=null && this.getCompanyId().equals(castOther.getCompanyId()) ) )
 && ( (this.getRaSealMaster()==castOther.getRaSealMaster()) || ( this.getRaSealMaster()!=null && castOther.getRaSealMaster()!=null && this.getRaSealMaster().equals(castOther.getRaSealMaster()) ) )
 && ( (this.getSupplierType()==castOther.getSupplierType()) || ( this.getSupplierType()!=null && castOther.getSupplierType()!=null && this.getSupplierType().equals(castOther.getSupplierType()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCompanyId() == null ? 0 : this.getCompanyId().hashCode() );
         result = 37 * result + ( getRaSealMaster() == null ? 0 : this.getRaSealMaster().hashCode() );
         result = 37 * result + ( getSupplierType() == null ? 0 : this.getSupplierType().hashCode() );
         return result;
   }   





}