package com.kjnext.hibernate;



/**
 * RaSealSupplier generated by MyEclipse - Hibernate Tools
 */

public class RaSealSupplier  implements java.io.Serializable {


    // Fields    

     private RaSealSupplierId id;
     private RaSealMaster raSealMaster;


    // Constructors

    /** default constructor */
    public RaSealSupplier() {
    }

	/** minimal constructor */
    public RaSealSupplier(RaSealSupplierId id) {
        this.id = id;
    }
    
    /** full constructor */
    public RaSealSupplier(RaSealSupplierId id, RaSealMaster raSealMaster) {
        this.id = id;
        this.raSealMaster = raSealMaster;
    }

   
    // Property accessors

    public RaSealSupplierId getId() {
        return this.id;
    }
    
    public void setId(RaSealSupplierId id) {
        this.id = id;
    }

    public RaSealMaster getRaSealMaster() {
        return this.raSealMaster;
    }
    
    public void setRaSealMaster(RaSealMaster raSealMaster) {
        this.raSealMaster = raSealMaster;
    }
   








}