package com.kjnext.hibernate;



/**
 * RaSealMaterial generated by MyEclipse - Hibernate Tools
 */

public class RaSealMaterial  implements java.io.Serializable {


    // Fields    

     private RaSealMaterialId id;


    // Constructors

    /** default constructor */
    public RaSealMaterial() {
    }

    
    /** full constructor */
    public RaSealMaterial(RaSealMaterialId id) {
        this.id = id;
    }

   
    // Property accessors

    public RaSealMaterialId getId() {
        return this.id;
    }
    
    public void setId(RaSealMaterialId id) {
        this.id = id;
    }
   








}