package com.kjnext.hibernate;



/**
 * RaSealBrand generated by MyEclipse - Hibernate Tools
 */

public class RaSealBrand  implements java.io.Serializable {


    // Fields    

     private RaSealBrandId id;
     private RaSealMaster raSealMaster;


    // Constructors

    /** default constructor */
    public RaSealBrand() {
    }

	/** minimal constructor */
    public RaSealBrand(RaSealBrandId id) {
        this.id = id;
    }
    
    /** full constructor */
    public RaSealBrand(RaSealBrandId id, RaSealMaster raSealMaster) {
        this.id = id;
        this.raSealMaster = raSealMaster;
    }

   
    // Property accessors

    public RaSealBrandId getId() {
        return this.id;
    }
    
    public void setId(RaSealBrandId id) {
        this.id = id;
    }

    public RaSealMaster getRaSealMaster() {
        return this.raSealMaster;
    }
    
    public void setRaSealMaster(RaSealMaster raSealMaster) {
        this.raSealMaster = raSealMaster;
    }
   








}