package com.kjnext.hibernate;



/**
 * RaSealBrandId generated by MyEclipse - Hibernate Tools
 */

public class RaSealBrandId  implements java.io.Serializable {


    // Fields    

     private RaSealMaster raSealMaster;
     private Integer brandId;


    // Constructors

    /** default constructor */
    public RaSealBrandId() {
    }

    
    /** full constructor */
    public RaSealBrandId(RaSealMaster raSealMaster, Integer brandId) {
        this.raSealMaster = raSealMaster;
        this.brandId = brandId;
    }

   
    // Property accessors

    public RaSealMaster getRaSealMaster() {
        return this.raSealMaster;
    }
    
    public void setRaSealMaster(RaSealMaster raSealMaster) {
        this.raSealMaster = raSealMaster;
    }

    public Integer getBrandId() {
        return this.brandId;
    }
    
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RaSealBrandId) ) return false;
		 RaSealBrandId castOther = ( RaSealBrandId ) other; 
         
		 return ( (this.getRaSealMaster()==castOther.getRaSealMaster()) || ( this.getRaSealMaster()!=null && castOther.getRaSealMaster()!=null && this.getRaSealMaster().equals(castOther.getRaSealMaster()) ) )
 && ( (this.getBrandId()==castOther.getBrandId()) || ( this.getBrandId()!=null && castOther.getBrandId()!=null && this.getBrandId().equals(castOther.getBrandId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRaSealMaster() == null ? 0 : this.getRaSealMaster().hashCode() );
         result = 37 * result + ( getBrandId() == null ? 0 : this.getBrandId().hashCode() );
         return result;
   }   





}