package com.kjnext.hibernate;



/**
 * RaSealState generated by MyEclipse - Hibernate Tools
 */

public class RaSealState  implements java.io.Serializable {


    // Fields    

     private RaSealStateId id;
     private RaStateMaster raStateMaster;
     private RaSealMaster raSealMaster;


    // Constructors

    /** default constructor */
    public RaSealState() {
    }

	/** minimal constructor */
    public RaSealState(RaSealStateId id) {
        this.id = id;
    }
    
    /** full constructor */
    public RaSealState(RaSealStateId id, RaStateMaster raStateMaster, RaSealMaster raSealMaster) {
        this.id = id;
        this.raStateMaster = raStateMaster;
        this.raSealMaster = raSealMaster;
    }

   
    // Property accessors

    public RaSealStateId getId() {
        return this.id;
    }
    
    public void setId(RaSealStateId id) {
        this.id = id;
    }

    public RaStateMaster getRaStateMaster() {
        return this.raStateMaster;
    }
    
    public void setRaStateMaster(RaStateMaster raStateMaster) {
        this.raStateMaster = raStateMaster;
    }

    public RaSealMaster getRaSealMaster() {
        return this.raSealMaster;
    }
    
    public void setRaSealMaster(RaSealMaster raSealMaster) {
        this.raSealMaster = raSealMaster;
    }
   








}