package com.kjnext.hibernate;



/**
 * RaSealProductId generated by MyEclipse - Hibernate Tools
 */

public class RaSealProductId  implements java.io.Serializable {


    // Fields    

     private RaSealMaster raSealMaster;
     private RaProductMaster raProductMaster;


    // Constructors

    /** default constructor */
    public RaSealProductId() {
    }

    
    /** full constructor */
    public RaSealProductId(RaSealMaster raSealMaster, RaProductMaster raProductMaster) {
        this.raSealMaster = raSealMaster;
        this.raProductMaster = raProductMaster;
    }

   
    // Property accessors

    public RaSealMaster getRaSealMaster() {
        return this.raSealMaster;
    }
    
    public void setRaSealMaster(RaSealMaster raSealMaster) {
        this.raSealMaster = raSealMaster;
    }

    public RaProductMaster getRaProductMaster() {
        return this.raProductMaster;
    }
    
    public void setRaProductMaster(RaProductMaster raProductMaster) {
        this.raProductMaster = raProductMaster;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RaSealProductId) ) return false;
		 RaSealProductId castOther = ( RaSealProductId ) other; 
         
		 return ( (this.getRaSealMaster()==castOther.getRaSealMaster()) || ( this.getRaSealMaster()!=null && castOther.getRaSealMaster()!=null && this.getRaSealMaster().equals(castOther.getRaSealMaster()) ) )
 && ( (this.getRaProductMaster()==castOther.getRaProductMaster()) || ( this.getRaProductMaster()!=null && castOther.getRaProductMaster()!=null && this.getRaProductMaster().equals(castOther.getRaProductMaster()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRaSealMaster() == null ? 0 : this.getRaSealMaster().hashCode() );
         result = 37 * result + ( getRaProductMaster() == null ? 0 : this.getRaProductMaster().hashCode() );
         return result;
   }   





}