package com.kjnext.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * RaSellingRegion generated by MyEclipse - Hibernate Tools
 */

public class RaSellingRegion  implements java.io.Serializable {


    // Fields    

     private Integer regionId;
     private String description;
     private String regionType;
     private String status;
     private Set raStateMasters = new HashSet(0);


    // Constructors

    /** default constructor */
    public RaSellingRegion() {
    }

	/** minimal constructor */
    public RaSellingRegion(Integer regionId) {
        this.regionId = regionId;
    }
    
    /** full constructor */
    public RaSellingRegion(Integer regionId, String description, String regionType, String status, Set raStateMasters) {
        this.regionId = regionId;
        this.description = description;
        this.regionType = regionType;
        this.status = status;
        this.raStateMasters = raStateMasters;
    }

   
    // Property accessors

    public Integer getRegionId() {
        return this.regionId;
    }
    
    public void setRegionId(Integer regionId) {
        this.regionId = regionId;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public String getRegionType() {
        return this.regionType;
    }
    
    public void setRegionType(String regionType) {
        this.regionType = regionType;
    }

    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    public Set getRaStateMasters() {
        return this.raStateMasters;
    }
    
    public void setRaStateMasters(Set raStateMasters) {
        this.raStateMasters = raStateMasters;
    }
   








}