package com.kjnext.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * RaStateMaster generated by MyEclipse - Hibernate Tools
 */

public class RaStateMaster  implements java.io.Serializable {


    // Fields    

     private Integer stateId;
     private RaSellingRegion raSellingRegion;
     private String description;
     private String stateStatus;
     private String stateType;
     private Set raTraceabilities = new HashSet(0);
     private Set raCompanyStates = new HashSet(0);
     private Set raSealStates = new HashSet(0);


    // Constructors

    /** default constructor */
    public RaStateMaster() {
    }

	/** minimal constructor */
    public RaStateMaster(Integer stateId) {
        this.stateId = stateId;
    }
    
    /** full constructor */
    public RaStateMaster(Integer stateId, RaSellingRegion raSellingRegion, String description, String stateStatus, String stateType, Set raTraceabilities, Set raCompanyStates, Set raSealStates) {
        this.stateId = stateId;
        this.raSellingRegion = raSellingRegion;
        this.description = description;
        this.stateStatus = stateStatus;
        this.stateType = stateType;
        this.raTraceabilities = raTraceabilities;
        this.raCompanyStates = raCompanyStates;
        this.raSealStates = raSealStates;
    }

   
    // Property accessors

    public Integer getStateId() {
        return this.stateId;
    }
    
    public void setStateId(Integer stateId) {
        this.stateId = stateId;
    }

    public RaSellingRegion getRaSellingRegion() {
        return this.raSellingRegion;
    }
    
    public void setRaSellingRegion(RaSellingRegion raSellingRegion) {
        this.raSellingRegion = raSellingRegion;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public String getStateStatus() {
        return this.stateStatus;
    }
    
    public void setStateStatus(String stateStatus) {
        this.stateStatus = stateStatus;
    }

    public String getStateType() {
        return this.stateType;
    }
    
    public void setStateType(String stateType) {
        this.stateType = stateType;
    }

    public Set getRaTraceabilities() {
        return this.raTraceabilities;
    }
    
    public void setRaTraceabilities(Set raTraceabilities) {
        this.raTraceabilities = raTraceabilities;
    }

    public Set getRaCompanyStates() {
        return this.raCompanyStates;
    }
    
    public void setRaCompanyStates(Set raCompanyStates) {
        this.raCompanyStates = raCompanyStates;
    }

    public Set getRaSealStates() {
        return this.raSealStates;
    }
    
    public void setRaSealStates(Set raSealStates) {
        this.raSealStates = raSealStates;
    }
   








}