package com.kjnext.hibernate;



/**
 * RaSubmodAccessId generated by MyEclipse - Hibernate Tools
 */

public class RaSubmodAccessId  implements java.io.Serializable {


    // Fields    

     private Integer subModuleId;
     private String roleShortName;


    // Constructors

    /** default constructor */
    public RaSubmodAccessId() {
    }

    
    /** full constructor */
    public RaSubmodAccessId(Integer subModuleId, String roleShortName) {
        this.subModuleId = subModuleId;
        this.roleShortName = roleShortName;
    }

   
    // Property accessors

    public Integer getSubModuleId() {
        return this.subModuleId;
    }
    
    public void setSubModuleId(Integer subModuleId) {
        this.subModuleId = subModuleId;
    }

    public String getRoleShortName() {
        return this.roleShortName;
    }
    
    public void setRoleShortName(String roleShortName) {
        this.roleShortName = roleShortName;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RaSubmodAccessId) ) return false;
		 RaSubmodAccessId castOther = ( RaSubmodAccessId ) other; 
         
		 return ( (this.getSubModuleId()==castOther.getSubModuleId()) || ( this.getSubModuleId()!=null && castOther.getSubModuleId()!=null && this.getSubModuleId().equals(castOther.getSubModuleId()) ) )
 && ( (this.getRoleShortName()==castOther.getRoleShortName()) || ( this.getRoleShortName()!=null && castOther.getRoleShortName()!=null && this.getRoleShortName().equals(castOther.getRoleShortName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSubModuleId() == null ? 0 : this.getSubModuleId().hashCode() );
         result = 37 * result + ( getRoleShortName() == null ? 0 : this.getRoleShortName().hashCode() );
         return result;
   }   





}