package com.kjnext.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * RaSubModule generated by MyEclipse - Hibernate Tools
 */

public class RaSubModule  implements java.io.Serializable {


    // Fields    

     private Integer subModuleId;
     private RaModuleMaster raModuleMaster;
     private String subModuleName;
     private Set raAclMasters = new HashSet(0);


    // Constructors

    /** default constructor */
    public RaSubModule() {
    }

	/** minimal constructor */
    public RaSubModule(Integer subModuleId) {
        this.subModuleId = subModuleId;
    }
    
    /** full constructor */
    public RaSubModule(Integer subModuleId, RaModuleMaster raModuleMaster, String subModuleName, Set raAclMasters) {
        this.subModuleId = subModuleId;
        this.raModuleMaster = raModuleMaster;
        this.subModuleName = subModuleName;
        this.raAclMasters = raAclMasters;
    }

   
    // Property accessors

    public Integer getSubModuleId() {
        return this.subModuleId;
    }
    
    public void setSubModuleId(Integer subModuleId) {
        this.subModuleId = subModuleId;
    }

    public RaModuleMaster getRaModuleMaster() {
        return this.raModuleMaster;
    }
    
    public void setRaModuleMaster(RaModuleMaster raModuleMaster) {
        this.raModuleMaster = raModuleMaster;
    }

    public String getSubModuleName() {
        return this.subModuleName;
    }
    
    public void setSubModuleName(String subModuleName) {
        this.subModuleName = subModuleName;
    }

    public Set getRaAclMasters() {
        return this.raAclMasters;
    }
    
    public void setRaAclMasters(Set raAclMasters) {
        this.raAclMasters = raAclMasters;
    }
   








}