package com.kjnext.hibernate;



/**
 * RaSubmodAccess generated by MyEclipse - Hibernate Tools
 */

public class RaSubmodAccess  implements java.io.Serializable {


    // Fields    

     private RaSubmodAccessId id;


    // Constructors

    /** default constructor */
    public RaSubmodAccess() {
    }

    
    /** full constructor */
    public RaSubmodAccess(RaSubmodAccessId id) {
        this.id = id;
    }

   
    // Property accessors

    public RaSubmodAccessId getId() {
        return this.id;
    }
    
    public void setId(RaSubmodAccessId id) {
        this.id = id;
    }
   








}