package com.kjnext.hibernate;

import java.util.Date;


/**
 * RaTraceabilityEditId generated by MyEclipse - Hibernate Tools
 */

public class RaTraceabilityEditId  implements java.io.Serializable {


    // Fields    

     private Integer transId;
     private Integer customerId;
     private Date transDate;
     private String buyerId;
     private String sellerId;
     private Integer originId;
     private Integer cropYearId;
     private Integer prBasisId;
     private String priceType;
     private Double price;
     private String priceUnit;
     private String prcieExchange;
     private Integer stateId;
     private Integer loadId;
     private Integer destPortId;
     private String orderType;
     private Integer deliveryMonthId;
     private Integer userId;
     private Integer noOfContainers;
     private String status;
     private Integer parentTransId;
     private Double premPrice;
     private String premPriceUom;


    // Constructors

    /** default constructor */
    public RaTraceabilityEditId() {
    }

    
    /** full constructor */
    public RaTraceabilityEditId(Integer transId, Integer customerId, Date transDate, String buyerId, String sellerId, Integer originId, Integer cropYearId, Integer prBasisId, String priceType, Double price, String priceUnit, String prcieExchange, Integer stateId, Integer loadId, Integer destPortId, String orderType, Integer deliveryMonthId, Integer userId, Integer noOfContainers, String status, Integer parentTransId, Double premPrice, String premPriceUom) {
        this.transId = transId;
        this.customerId = customerId;
        this.transDate = transDate;
        this.buyerId = buyerId;
        this.sellerId = sellerId;
        this.originId = originId;
        this.cropYearId = cropYearId;
        this.prBasisId = prBasisId;
        this.priceType = priceType;
        this.price = price;
        this.priceUnit = priceUnit;
        this.prcieExchange = prcieExchange;
        this.stateId = stateId;
        this.loadId = loadId;
        this.destPortId = destPortId;
        this.orderType = orderType;
        this.deliveryMonthId = deliveryMonthId;
        this.userId = userId;
        this.noOfContainers = noOfContainers;
        this.status = status;
        this.parentTransId = parentTransId;
        this.premPrice = premPrice;
        this.premPriceUom = premPriceUom;
    }

   
    // Property accessors

    public Integer getTransId() {
        return this.transId;
    }
    
    public void setTransId(Integer transId) {
        this.transId = transId;
    }

    public Integer getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    public Date getTransDate() {
        return this.transDate;
    }
    
    public void setTransDate(Date transDate) {
        this.transDate = transDate;
    }

    public String getBuyerId() {
        return this.buyerId;
    }
    
    public void setBuyerId(String buyerId) {
        this.buyerId = buyerId;
    }

    public String getSellerId() {
        return this.sellerId;
    }
    
    public void setSellerId(String sellerId) {
        this.sellerId = sellerId;
    }

    public Integer getOriginId() {
        return this.originId;
    }
    
    public void setOriginId(Integer originId) {
        this.originId = originId;
    }

    public Integer getCropYearId() {
        return this.cropYearId;
    }
    
    public void setCropYearId(Integer cropYearId) {
        this.cropYearId = cropYearId;
    }

    public Integer getPrBasisId() {
        return this.prBasisId;
    }
    
    public void setPrBasisId(Integer prBasisId) {
        this.prBasisId = prBasisId;
    }

    public String getPriceType() {
        return this.priceType;
    }
    
    public void setPriceType(String priceType) {
        this.priceType = priceType;
    }

    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }

    public String getPriceUnit() {
        return this.priceUnit;
    }
    
    public void setPriceUnit(String priceUnit) {
        this.priceUnit = priceUnit;
    }

    public String getPrcieExchange() {
        return this.prcieExchange;
    }
    
    public void setPrcieExchange(String prcieExchange) {
        this.prcieExchange = prcieExchange;
    }

    public Integer getStateId() {
        return this.stateId;
    }
    
    public void setStateId(Integer stateId) {
        this.stateId = stateId;
    }

    public Integer getLoadId() {
        return this.loadId;
    }
    
    public void setLoadId(Integer loadId) {
        this.loadId = loadId;
    }

    public Integer getDestPortId() {
        return this.destPortId;
    }
    
    public void setDestPortId(Integer destPortId) {
        this.destPortId = destPortId;
    }

    public String getOrderType() {
        return this.orderType;
    }
    
    public void setOrderType(String orderType) {
        this.orderType = orderType;
    }

    public Integer getDeliveryMonthId() {
        return this.deliveryMonthId;
    }
    
    public void setDeliveryMonthId(Integer deliveryMonthId) {
        this.deliveryMonthId = deliveryMonthId;
    }

    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getNoOfContainers() {
        return this.noOfContainers;
    }
    
    public void setNoOfContainers(Integer noOfContainers) {
        this.noOfContainers = noOfContainers;
    }

    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    public Integer getParentTransId() {
        return this.parentTransId;
    }
    
    public void setParentTransId(Integer parentTransId) {
        this.parentTransId = parentTransId;
    }

    public Double getPremPrice() {
        return this.premPrice;
    }
    
    public void setPremPrice(Double premPrice) {
        this.premPrice = premPrice;
    }

    public String getPremPriceUom() {
        return this.premPriceUom;
    }
    
    public void setPremPriceUom(String premPriceUom) {
        this.premPriceUom = premPriceUom;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RaTraceabilityEditId) ) return false;
		 RaTraceabilityEditId castOther = ( RaTraceabilityEditId ) other; 
         
		 return ( (this.getTransId()==castOther.getTransId()) || ( this.getTransId()!=null && castOther.getTransId()!=null && this.getTransId().equals(castOther.getTransId()) ) )
 && ( (this.getCustomerId()==castOther.getCustomerId()) || ( this.getCustomerId()!=null && castOther.getCustomerId()!=null && this.getCustomerId().equals(castOther.getCustomerId()) ) )
 && ( (this.getTransDate()==castOther.getTransDate()) || ( this.getTransDate()!=null && castOther.getTransDate()!=null && this.getTransDate().equals(castOther.getTransDate()) ) )
 && ( (this.getBuyerId()==castOther.getBuyerId()) || ( this.getBuyerId()!=null && castOther.getBuyerId()!=null && this.getBuyerId().equals(castOther.getBuyerId()) ) )
 && ( (this.getSellerId()==castOther.getSellerId()) || ( this.getSellerId()!=null && castOther.getSellerId()!=null && this.getSellerId().equals(castOther.getSellerId()) ) )
 && ( (this.getOriginId()==castOther.getOriginId()) || ( this.getOriginId()!=null && castOther.getOriginId()!=null && this.getOriginId().equals(castOther.getOriginId()) ) )
 && ( (this.getCropYearId()==castOther.getCropYearId()) || ( this.getCropYearId()!=null && castOther.getCropYearId()!=null && this.getCropYearId().equals(castOther.getCropYearId()) ) )
 && ( (this.getPrBasisId()==castOther.getPrBasisId()) || ( this.getPrBasisId()!=null && castOther.getPrBasisId()!=null && this.getPrBasisId().equals(castOther.getPrBasisId()) ) )
 && ( (this.getPriceType()==castOther.getPriceType()) || ( this.getPriceType()!=null && castOther.getPriceType()!=null && this.getPriceType().equals(castOther.getPriceType()) ) )
 && ( (this.getPrice()==castOther.getPrice()) || ( this.getPrice()!=null && castOther.getPrice()!=null && this.getPrice().equals(castOther.getPrice()) ) )
 && ( (this.getPriceUnit()==castOther.getPriceUnit()) || ( this.getPriceUnit()!=null && castOther.getPriceUnit()!=null && this.getPriceUnit().equals(castOther.getPriceUnit()) ) )
 && ( (this.getPrcieExchange()==castOther.getPrcieExchange()) || ( this.getPrcieExchange()!=null && castOther.getPrcieExchange()!=null && this.getPrcieExchange().equals(castOther.getPrcieExchange()) ) )
 && ( (this.getStateId()==castOther.getStateId()) || ( this.getStateId()!=null && castOther.getStateId()!=null && this.getStateId().equals(castOther.getStateId()) ) )
 && ( (this.getLoadId()==castOther.getLoadId()) || ( this.getLoadId()!=null && castOther.getLoadId()!=null && this.getLoadId().equals(castOther.getLoadId()) ) )
 && ( (this.getDestPortId()==castOther.getDestPortId()) || ( this.getDestPortId()!=null && castOther.getDestPortId()!=null && this.getDestPortId().equals(castOther.getDestPortId()) ) )
 && ( (this.getOrderType()==castOther.getOrderType()) || ( this.getOrderType()!=null && castOther.getOrderType()!=null && this.getOrderType().equals(castOther.getOrderType()) ) )
 && ( (this.getDeliveryMonthId()==castOther.getDeliveryMonthId()) || ( this.getDeliveryMonthId()!=null && castOther.getDeliveryMonthId()!=null && this.getDeliveryMonthId().equals(castOther.getDeliveryMonthId()) ) )
 && ( (this.getUserId()==castOther.getUserId()) || ( this.getUserId()!=null && castOther.getUserId()!=null && this.getUserId().equals(castOther.getUserId()) ) )
 && ( (this.getNoOfContainers()==castOther.getNoOfContainers()) || ( this.getNoOfContainers()!=null && castOther.getNoOfContainers()!=null && this.getNoOfContainers().equals(castOther.getNoOfContainers()) ) )
 && ( (this.getStatus()==castOther.getStatus()) || ( this.getStatus()!=null && castOther.getStatus()!=null && this.getStatus().equals(castOther.getStatus()) ) )
 && ( (this.getParentTransId()==castOther.getParentTransId()) || ( this.getParentTransId()!=null && castOther.getParentTransId()!=null && this.getParentTransId().equals(castOther.getParentTransId()) ) )
 && ( (this.getPremPrice()==castOther.getPremPrice()) || ( this.getPremPrice()!=null && castOther.getPremPrice()!=null && this.getPremPrice().equals(castOther.getPremPrice()) ) )
 && ( (this.getPremPriceUom()==castOther.getPremPriceUom()) || ( this.getPremPriceUom()!=null && castOther.getPremPriceUom()!=null && this.getPremPriceUom().equals(castOther.getPremPriceUom()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTransId() == null ? 0 : this.getTransId().hashCode() );
         result = 37 * result + ( getCustomerId() == null ? 0 : this.getCustomerId().hashCode() );
         result = 37 * result + ( getTransDate() == null ? 0 : this.getTransDate().hashCode() );
         result = 37 * result + ( getBuyerId() == null ? 0 : this.getBuyerId().hashCode() );
         result = 37 * result + ( getSellerId() == null ? 0 : this.getSellerId().hashCode() );
         result = 37 * result + ( getOriginId() == null ? 0 : this.getOriginId().hashCode() );
         result = 37 * result + ( getCropYearId() == null ? 0 : this.getCropYearId().hashCode() );
         result = 37 * result + ( getPrBasisId() == null ? 0 : this.getPrBasisId().hashCode() );
         result = 37 * result + ( getPriceType() == null ? 0 : this.getPriceType().hashCode() );
         result = 37 * result + ( getPrice() == null ? 0 : this.getPrice().hashCode() );
         result = 37 * result + ( getPriceUnit() == null ? 0 : this.getPriceUnit().hashCode() );
         result = 37 * result + ( getPrcieExchange() == null ? 0 : this.getPrcieExchange().hashCode() );
         result = 37 * result + ( getStateId() == null ? 0 : this.getStateId().hashCode() );
         result = 37 * result + ( getLoadId() == null ? 0 : this.getLoadId().hashCode() );
         result = 37 * result + ( getDestPortId() == null ? 0 : this.getDestPortId().hashCode() );
         result = 37 * result + ( getOrderType() == null ? 0 : this.getOrderType().hashCode() );
         result = 37 * result + ( getDeliveryMonthId() == null ? 0 : this.getDeliveryMonthId().hashCode() );
         result = 37 * result + ( getUserId() == null ? 0 : this.getUserId().hashCode() );
         result = 37 * result + ( getNoOfContainers() == null ? 0 : this.getNoOfContainers().hashCode() );
         result = 37 * result + ( getStatus() == null ? 0 : this.getStatus().hashCode() );
         result = 37 * result + ( getParentTransId() == null ? 0 : this.getParentTransId().hashCode() );
         result = 37 * result + ( getPremPrice() == null ? 0 : this.getPremPrice().hashCode() );
         result = 37 * result + ( getPremPriceUom() == null ? 0 : this.getPremPriceUom().hashCode() );
         return result;
   }   





}