package com.kjnext.hibernate;



/**
 * RaTraceabilityEdit generated by MyEclipse - Hibernate Tools
 */

public class RaTraceabilityEdit  implements java.io.Serializable {


    // Fields    

     private RaTraceabilityEditId id;


    // Constructors

    /** default constructor */
    public RaTraceabilityEdit() {
    }

    
    /** full constructor */
    public RaTraceabilityEdit(RaTraceabilityEditId id) {
        this.id = id;
    }

   
    // Property accessors

    public RaTraceabilityEditId getId() {
        return this.id;
    }
    
    public void setId(RaTraceabilityEditId id) {
        this.id = id;
    }
   








}