package com.kjnext.hibernate;

import java.util.Date;


/**
 * RaTraceOffers generated by MyEclipse - Hibernate Tools
 */

public class RaTraceOffers  implements java.io.Serializable {


    // Fields    

     private Integer offerId;
     private RaGradeMaster raGradeMaster;
     private RaOriginMaster raOriginMaster;
     private RaDestinationPort raDestinationPort;
     private RaCompanyMaster raCompanyMaster;
     private Date offerDate;
     private Date availabilityDate;
     private Date expirationDate;
     private Integer userId;
     private String firstName;
     private String lastName;
     private String email;
     private String phone;
     private Integer offerQty;
     private String qtyUom;
     private Integer offerPrice;
     private String offerPriceUom;
     private Integer countryId;
     private String city;
     private String comments;
     private Integer producerId;
     private Integer loadId;
     private Integer productId;
     private String farmName;
     private String otherCity;
     private Integer farmId;


    // Constructors

    /** default constructor */
    public RaTraceOffers() {
    }

	/** minimal constructor */
    public RaTraceOffers(Integer offerId) {
        this.offerId = offerId;
    }
    
    /** full constructor */
    public RaTraceOffers(Integer offerId, RaGradeMaster raGradeMaster, RaOriginMaster raOriginMaster, RaDestinationPort raDestinationPort, RaCompanyMaster raCompanyMaster, Date offerDate, Date availabilityDate, Date expirationDate, Integer userId, String firstName, String lastName, String email, String phone, Integer offerQty, String qtyUom, Integer offerPrice, String offerPriceUom, Integer countryId, String city, String comments, Integer producerId, Integer loadId, Integer productId, String farmName, String otherCity, Integer farmId) {
        this.offerId = offerId;
        this.raGradeMaster = raGradeMaster;
        this.raOriginMaster = raOriginMaster;
        this.raDestinationPort = raDestinationPort;
        this.raCompanyMaster = raCompanyMaster;
        this.offerDate = offerDate;
        this.availabilityDate = availabilityDate;
        this.expirationDate = expirationDate;
        this.userId = userId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.phone = phone;
        this.offerQty = offerQty;
        this.qtyUom = qtyUom;
        this.offerPrice = offerPrice;
        this.offerPriceUom = offerPriceUom;
        this.countryId = countryId;
        this.city = city;
        this.comments = comments;
        this.producerId = producerId;
        this.loadId = loadId;
        this.productId = productId;
        this.farmName = farmName;
        this.otherCity = otherCity;
        this.farmId = farmId;
    }

   
    // Property accessors

    public Integer getOfferId() {
        return this.offerId;
    }
    
    public void setOfferId(Integer offerId) {
        this.offerId = offerId;
    }

    public RaGradeMaster getRaGradeMaster() {
        return this.raGradeMaster;
    }
    
    public void setRaGradeMaster(RaGradeMaster raGradeMaster) {
        this.raGradeMaster = raGradeMaster;
    }

    public RaOriginMaster getRaOriginMaster() {
        return this.raOriginMaster;
    }
    
    public void setRaOriginMaster(RaOriginMaster raOriginMaster) {
        this.raOriginMaster = raOriginMaster;
    }

    public RaDestinationPort getRaDestinationPort() {
        return this.raDestinationPort;
    }
    
    public void setRaDestinationPort(RaDestinationPort raDestinationPort) {
        this.raDestinationPort = raDestinationPort;
    }

    public RaCompanyMaster getRaCompanyMaster() {
        return this.raCompanyMaster;
    }
    
    public void setRaCompanyMaster(RaCompanyMaster raCompanyMaster) {
        this.raCompanyMaster = raCompanyMaster;
    }

    public Date getOfferDate() {
        return this.offerDate;
    }
    
    public void setOfferDate(Date offerDate) {
        this.offerDate = offerDate;
    }

    public Date getAvailabilityDate() {
        return this.availabilityDate;
    }
    
    public void setAvailabilityDate(Date availabilityDate) {
        this.availabilityDate = availabilityDate;
    }

    public Date getExpirationDate() {
        return this.expirationDate;
    }
    
    public void setExpirationDate(Date expirationDate) {
        this.expirationDate = expirationDate;
    }

    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    public Integer getOfferQty() {
        return this.offerQty;
    }
    
    public void setOfferQty(Integer offerQty) {
        this.offerQty = offerQty;
    }

    public String getQtyUom() {
        return this.qtyUom;
    }
    
    public void setQtyUom(String qtyUom) {
        this.qtyUom = qtyUom;
    }

    public Integer getOfferPrice() {
        return this.offerPrice;
    }
    
    public void setOfferPrice(Integer offerPrice) {
        this.offerPrice = offerPrice;
    }

    public String getOfferPriceUom() {
        return this.offerPriceUom;
    }
    
    public void setOfferPriceUom(String offerPriceUom) {
        this.offerPriceUom = offerPriceUom;
    }

    public Integer getCountryId() {
        return this.countryId;
    }
    
    public void setCountryId(Integer countryId) {
        this.countryId = countryId;
    }

    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }

    public Integer getProducerId() {
        return this.producerId;
    }
    
    public void setProducerId(Integer producerId) {
        this.producerId = producerId;
    }

    public Integer getLoadId() {
        return this.loadId;
    }
    
    public void setLoadId(Integer loadId) {
        this.loadId = loadId;
    }

    public Integer getProductId() {
        return this.productId;
    }
    
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    public String getFarmName() {
        return this.farmName;
    }
    
    public void setFarmName(String farmName) {
        this.farmName = farmName;
    }

    public String getOtherCity() {
        return this.otherCity;
    }
    
    public void setOtherCity(String otherCity) {
        this.otherCity = otherCity;
    }

    public Integer getFarmId() {
        return this.farmId;
    }
    
    public void setFarmId(Integer farmId) {
        this.farmId = farmId;
    }
   








}