package com.kjnext.hibernate;

import java.util.Date;


/**
 * RaTraceConsumeId generated by MyEclipse - Hibernate Tools
 */

public class RaTraceConsumeId  implements java.io.Serializable {


    // Fields    

     private Integer transId;
     private Integer containerId;
     private Integer consumeQty;
     private Integer brandId;
     private Date consumeDate;


    // Constructors

    /** default constructor */
    public RaTraceConsumeId() {
    }

    
    /** full constructor */
    public RaTraceConsumeId(Integer transId, Integer containerId, Integer consumeQty, Integer brandId, Date consumeDate) {
        this.transId = transId;
        this.containerId = containerId;
        this.consumeQty = consumeQty;
        this.brandId = brandId;
        this.consumeDate = consumeDate;
    }

   
    // Property accessors

    public Integer getTransId() {
        return this.transId;
    }
    
    public void setTransId(Integer transId) {
        this.transId = transId;
    }

    public Integer getContainerId() {
        return this.containerId;
    }
    
    public void setContainerId(Integer containerId) {
        this.containerId = containerId;
    }

    public Integer getConsumeQty() {
        return this.consumeQty;
    }
    
    public void setConsumeQty(Integer consumeQty) {
        this.consumeQty = consumeQty;
    }

    public Integer getBrandId() {
        return this.brandId;
    }
    
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    public Date getConsumeDate() {
        return this.consumeDate;
    }
    
    public void setConsumeDate(Date consumeDate) {
        this.consumeDate = consumeDate;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RaTraceConsumeId) ) return false;
		 RaTraceConsumeId castOther = ( RaTraceConsumeId ) other; 
         
		 return ( (this.getTransId()==castOther.getTransId()) || ( this.getTransId()!=null && castOther.getTransId()!=null && this.getTransId().equals(castOther.getTransId()) ) )
 && ( (this.getContainerId()==castOther.getContainerId()) || ( this.getContainerId()!=null && castOther.getContainerId()!=null && this.getContainerId().equals(castOther.getContainerId()) ) )
 && ( (this.getConsumeQty()==castOther.getConsumeQty()) || ( this.getConsumeQty()!=null && castOther.getConsumeQty()!=null && this.getConsumeQty().equals(castOther.getConsumeQty()) ) )
 && ( (this.getBrandId()==castOther.getBrandId()) || ( this.getBrandId()!=null && castOther.getBrandId()!=null && this.getBrandId().equals(castOther.getBrandId()) ) )
 && ( (this.getConsumeDate()==castOther.getConsumeDate()) || ( this.getConsumeDate()!=null && castOther.getConsumeDate()!=null && this.getConsumeDate().equals(castOther.getConsumeDate()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTransId() == null ? 0 : this.getTransId().hashCode() );
         result = 37 * result + ( getContainerId() == null ? 0 : this.getContainerId().hashCode() );
         result = 37 * result + ( getConsumeQty() == null ? 0 : this.getConsumeQty().hashCode() );
         result = 37 * result + ( getBrandId() == null ? 0 : this.getBrandId().hashCode() );
         result = 37 * result + ( getConsumeDate() == null ? 0 : this.getConsumeDate().hashCode() );
         return result;
   }   





}