package com.kjnext.hibernate;



/**
 * RaTraceConsume generated by MyEclipse - Hibernate Tools
 */

public class RaTraceConsume  implements java.io.Serializable {


    // Fields    

     private RaTraceConsumeId id;


    // Constructors

    /** default constructor */
    public RaTraceConsume() {
    }

    
    /** full constructor */
    public RaTraceConsume(RaTraceConsumeId id) {
        this.id = id;
    }

   
    // Property accessors

    public RaTraceConsumeId getId() {
        return this.id;
    }
    
    public void setId(RaTraceConsumeId id) {
        this.id = id;
    }
   








}