package com.kjnext.hibernate;



/**
 * RaUnitMeasures generated by MyEclipse - Hibernate Tools
 */

public class RaUnitMeasures  implements java.io.Serializable {


    // Fields    

     private RaUnitMeasuresId id;


    // Constructors

    /** default constructor */
    public RaUnitMeasures() {
    }

    
    /** full constructor */
    public RaUnitMeasures(RaUnitMeasuresId id) {
        this.id = id;
    }

   
    // Property accessors

    public RaUnitMeasuresId getId() {
        return this.id;
    }
    
    public void setId(RaUnitMeasuresId id) {
        this.id = id;
    }
   








}