package com.kjnext.hibernate;



/**
 * RaUnitConv generated by MyEclipse - Hibernate Tools
 */

public class RaUnitConv  implements java.io.Serializable {


    // Fields    

     private RaUnitConvId id;


    // Constructors

    /** default constructor */
    public RaUnitConv() {
    }

    
    /** full constructor */
    public RaUnitConv(RaUnitConvId id) {
        this.id = id;
    }

   
    // Property accessors

    public RaUnitConvId getId() {
        return this.id;
    }
    
    public void setId(RaUnitConvId id) {
        this.id = id;
    }
   








}