package com.kjnext.hibernate;



/**
 * RaUnitConvId generated by MyEclipse - Hibernate Tools
 */

public class RaUnitConvId  implements java.io.Serializable {


    // Fields    

     private String fromUnit;
     private String toUnit;
     private Double convFactor;


    // Constructors

    /** default constructor */
    public RaUnitConvId() {
    }

    
    /** full constructor */
    public RaUnitConvId(String fromUnit, String toUnit, Double convFactor) {
        this.fromUnit = fromUnit;
        this.toUnit = toUnit;
        this.convFactor = convFactor;
    }

   
    // Property accessors

    public String getFromUnit() {
        return this.fromUnit;
    }
    
    public void setFromUnit(String fromUnit) {
        this.fromUnit = fromUnit;
    }

    public String getToUnit() {
        return this.toUnit;
    }
    
    public void setToUnit(String toUnit) {
        this.toUnit = toUnit;
    }

    public Double getConvFactor() {
        return this.convFactor;
    }
    
    public void setConvFactor(Double convFactor) {
        this.convFactor = convFactor;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RaUnitConvId) ) return false;
		 RaUnitConvId castOther = ( RaUnitConvId ) other; 
         
		 return ( (this.getFromUnit()==castOther.getFromUnit()) || ( this.getFromUnit()!=null && castOther.getFromUnit()!=null && this.getFromUnit().equals(castOther.getFromUnit()) ) )
 && ( (this.getToUnit()==castOther.getToUnit()) || ( this.getToUnit()!=null && castOther.getToUnit()!=null && this.getToUnit().equals(castOther.getToUnit()) ) )
 && ( (this.getConvFactor()==castOther.getConvFactor()) || ( this.getConvFactor()!=null && castOther.getConvFactor()!=null && this.getConvFactor().equals(castOther.getConvFactor()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getFromUnit() == null ? 0 : this.getFromUnit().hashCode() );
         result = 37 * result + ( getToUnit() == null ? 0 : this.getToUnit().hashCode() );
         result = 37 * result + ( getConvFactor() == null ? 0 : this.getConvFactor().hashCode() );
         return result;
   }   





}