package com.kjnext.hibernate;



/**
 * RaUserAcl generated by MyEclipse - Hibernate Tools
 */

public class RaUserAcl  implements java.io.Serializable {


    // Fields    

     private RaUserAclId id;
     private RaUserMaster raUserMaster;
     private RaAclMaster raAclMaster;


    // Constructors

    /** default constructor */
    public RaUserAcl() {
    }

	/** minimal constructor */
    public RaUserAcl(RaUserAclId id) {
        this.id = id;
    }
    
    /** full constructor */
    public RaUserAcl(RaUserAclId id, RaUserMaster raUserMaster, RaAclMaster raAclMaster) {
        this.id = id;
        this.raUserMaster = raUserMaster;
        this.raAclMaster = raAclMaster;
    }

   
    // Property accessors

    public RaUserAclId getId() {
        return this.id;
    }
    
    public void setId(RaUserAclId id) {
        this.id = id;
    }

    public RaUserMaster getRaUserMaster() {
        return this.raUserMaster;
    }
    
    public void setRaUserMaster(RaUserMaster raUserMaster) {
        this.raUserMaster = raUserMaster;
    }

    public RaAclMaster getRaAclMaster() {
        return this.raAclMaster;
    }
    
    public void setRaAclMaster(RaAclMaster raAclMaster) {
        this.raAclMaster = raAclMaster;
    }
   








}