package com.kjnext.hibernate;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * RaUserMaster generated by MyEclipse - Hibernate Tools
 */

public class RaUserMaster  implements java.io.Serializable {


    // Fields    

     private Integer userId;
     public RaCompanyMaster raCompanyMaster;
     private String loginName;
     private Integer producerId;
     private Date createDate;
     private String password;
     private Date modifyDate;
     private String firstName;
     private String userStatus;
     private String lastName;
     private String position;
     private String officeAddress;
     private String city;
     private String district;
     private String zip;
     private String state;
     private String phone;
     private String fax;
     private String email;
     private String comments;
     private String userType;
     private Set raUserAcls = new HashSet(0);


    // Constructors

    /** default constructor */
    public RaUserMaster() {
    }

	/** minimal constructor */
    public RaUserMaster(Integer userId, String password, String firstName, String state, String email) {
        this.userId = userId;
        this.password = password;
        this.firstName = firstName;
        this.state = state;
        this.email = email;
    }
    
    /** full constructor */
    public RaUserMaster(Integer userId, RaCompanyMaster raCompanyMaster, String loginName, Integer producerId, Date createDate, String password, Date modifyDate, String firstName, String userStatus, String lastName, String position, String officeAddress, String city, String district, String zip, String state, String phone, String fax, String email, String comments, String userType, Set raUserAcls) {
        this.userId = userId;
        this.raCompanyMaster = raCompanyMaster;
        this.loginName = loginName;
        this.producerId = producerId;
        this.createDate = createDate;
        this.password = password;
        this.modifyDate = modifyDate;
        this.firstName = firstName;
        this.userStatus = userStatus;
        this.lastName = lastName;
        this.position = position;
        this.officeAddress = officeAddress;
        this.city = city;
        this.district = district;
        this.zip = zip;
        this.state = state;
        this.phone = phone;
        this.fax = fax;
        this.email = email;
        this.comments = comments;
        this.userType = userType;
        this.raUserAcls = raUserAcls;
    }

   
    // Property accessors

    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public RaCompanyMaster getRaCompanyMaster() {
        return this.raCompanyMaster;
    }
    
    public void setRaCompanyMaster(RaCompanyMaster raCompanyMaster) {
        this.raCompanyMaster = raCompanyMaster;
    }

    public String getLoginName() {
        return this.loginName;
    }
    
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    public Integer getProducerId() {
        return this.producerId;
    }
    
    public void setProducerId(Integer producerId) {
        this.producerId = producerId;
    }

    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    public Date getModifyDate() {
        return this.modifyDate;
    }
    
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getUserStatus() {
        return this.userStatus;
    }
    
    public void setUserStatus(String userStatus) {
        this.userStatus = userStatus;
    }

    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getPosition() {
        return this.position;
    }
    
    public void setPosition(String position) {
        this.position = position;
    }

    public String getOfficeAddress() {
        return this.officeAddress;
    }
    
    public void setOfficeAddress(String officeAddress) {
        this.officeAddress = officeAddress;
    }

    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    public String getDistrict() {
        return this.district;
    }
    
    public void setDistrict(String district) {
        this.district = district;
    }

    public String getZip() {
        return this.zip;
    }
    
    public void setZip(String zip) {
        this.zip = zip;
    }

    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }

    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }

    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }

    public String getUserType() {
        return this.userType;
    }
    
    public void setUserType(String userType) {
        this.userType = userType;
    }

    public Set getRaUserAcls() {
        return this.raUserAcls;
    }
    
    public void setRaUserAcls(Set raUserAcls) {
        this.raUserAcls = raUserAcls;
    }
   








}