package com.kjnext.hibernate;



/**
 * RaUserAclId generated by MyEclipse - Hibernate Tools
 */

public class RaUserAclId  implements java.io.Serializable {


    // Fields    

     private RaAclMaster raAclMaster;
     private RaUserMaster raUserMaster;


    // Constructors

    /** default constructor */
    public RaUserAclId() {
    }

    
    /** full constructor */
    public RaUserAclId(RaAclMaster raAclMaster, RaUserMaster raUserMaster) {
        this.raAclMaster = raAclMaster;
        this.raUserMaster = raUserMaster;
    }

   
    // Property accessors

    public RaAclMaster getRaAclMaster() {
        return this.raAclMaster;
    }
    
    public void setRaAclMaster(RaAclMaster raAclMaster) {
        this.raAclMaster = raAclMaster;
    }

    public RaUserMaster getRaUserMaster() {
        return this.raUserMaster;
    }
    
    public void setRaUserMaster(RaUserMaster raUserMaster) {
        this.raUserMaster = raUserMaster;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RaUserAclId) ) return false;
		 RaUserAclId castOther = ( RaUserAclId ) other; 
         
		 return ( (this.getRaAclMaster()==castOther.getRaAclMaster()) || ( this.getRaAclMaster()!=null && castOther.getRaAclMaster()!=null && this.getRaAclMaster().equals(castOther.getRaAclMaster()) ) )
 && ( (this.getRaUserMaster()==castOther.getRaUserMaster()) || ( this.getRaUserMaster()!=null && castOther.getRaUserMaster()!=null && this.getRaUserMaster().equals(castOther.getRaUserMaster()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRaAclMaster() == null ? 0 : this.getRaAclMaster().hashCode() );
         result = 37 * result + ( getRaUserMaster() == null ? 0 : this.getRaUserMaster().hashCode() );
         return result;
   }   





}